-- Silver/Gold Provenance Audit — Staging layer (10 views)
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- Schemas: staging views = "staging"; silver tables = "silver"; gold = "gold"; dbt seeds = "public" (us_state_abbr, country_iso).
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- staging_text_column_type_sweep   [type]   target: staging.* (all stg_* views)
-- purpose : Confirm every staging column's emitted data type matches the produced/documented type (text for normalized free-text, timestamptz for coerced dates, integer where cast, jsonb for arrays). Schema-agnostic information_schema sweep cannot silently miss a column.
-- CONFORMS: Free-text/normalized cols = 'text'; announced_at/published_at/closed_at/*_dt/case_*_date/in_business/out_of_business/date_modified/latest_mpi_active_date/grant_date/extraction_timestamp = 'timestamp with time zone'; stg_uscg_recalls.units = 'integer'; stg_*_recalls.products/manufacturers/.../injuries and activities/dbas = 'jsonb'; recall_product_id = 'text'. No surprise numeric/boolean types on raw passthrough columns. NB staging models are views, so information_schema reflects the resolved view column types.
-- ----------------------------------------------------------------------------------
select table_name, column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'staging'
  and table_name in (
    'stg_cpsc_recalls','stg_fda_recalls','stg_fda_press_releases',
    'stg_nhtsa_recalls','stg_nhtsa_recalls_current','stg_uscg_recalls',
    'stg_uscg_manufacturers','stg_uscg_manufacturer_details',
    'stg_usda_fsis_recalls','stg_usda_fsis_establishments')
order by table_name, ordinal_position;

-- ----------------------------------------------------------------------------------
-- staging_empty_string_and_whitespace_sweep   [empty_string]   target: staging raw-passthrough text columns that do NOT nullif at staging
-- purpose : Extend the existing empty-string probe to THIS group: count '' and whitespace-only per text column to (a) confirm nullif-wrapped columns carry zero '', (b) measure the raw-passthrough columns (stg_usda classification/recall_type, stg_usda_establishments county/geolocation/city/state/zip/status_regulated_est, stg_fda firm_legal_nam/firm_fei_num/firm_surviving_fei) that DON'T nullif at staging.
-- CONFORMS: nullif-wrapped staging columns: n_empty = 0. status_regulated_est.n_empty = the active-establishment count (~90%, INTENTIONAL — '' is meaningful here, do NOT treat as a defect). classification/recall_type/county/geolocation: expected n_empty = 0 if the source never blanks them (validates the 'always populated' assumption); any n_empty > 0 confirms the raw-passthrough leak. n_whitespace should be 0 everywhere.
-- ----------------------------------------------------------------------------------
select 'stg_usda_fsis_recalls.classification' as col,
       count(*) filter (where classification = '') as n_empty,
       count(*) filter (where classification <> '' and classification ~ '^\s+$') as n_whitespace
from staging.stg_usda_fsis_recalls
union all
select 'stg_usda_fsis_recalls.recall_type',
       count(*) filter (where recall_type = ''),
       count(*) filter (where recall_type <> '' and recall_type ~ '^\s+$')
from staging.stg_usda_fsis_recalls
union all
select 'stg_usda_fsis_establishments.county',
       count(*) filter (where county = ''),
       count(*) filter (where county <> '' and county ~ '^\s+$')
from staging.stg_usda_fsis_establishments
union all
select 'stg_usda_fsis_establishments.geolocation',
       count(*) filter (where geolocation = ''),
       count(*) filter (where geolocation <> '' and geolocation ~ '^\s+$')
from staging.stg_usda_fsis_establishments
union all
select 'stg_usda_fsis_establishments.status_regulated_est',
       count(*) filter (where status_regulated_est = ''),
       count(*) filter (where status_regulated_est <> '' and status_regulated_est ~ '^\s+$')
from staging.stg_usda_fsis_establishments;

-- ----------------------------------------------------------------------------------
-- staging_freetext_passthrough_empty_string   [empty_string]   target: staging.stg_cpsc_recalls / stg_nhtsa_recalls free-text
-- purpose : Measure '' / whitespace on the CPSC + NHTSA raw free-text staging columns that are DELIBERATELY left raw at staging (title/description; desc_defect/conequence_defect/corrective_action/notes/fmvss). Confirms the empty strings live at staging (expected) and are removed only downstream in the serving model — so the audit can verify the layering, not re-flag staging as broken.
-- CONFORMS: n_empty MAY be > 0 here (CPSC/NHTSA staging is RAW by design per ADR 0027 — the '' -> NULL happens in the serving model, already fixed). This query DOCUMENTS the staging-level '' population; it is NOT a failure at staging. The companion serving-layer check (recall_event/recall_product) must show 0 for the corresponding served columns.
-- ----------------------------------------------------------------------------------
select 'stg_cpsc.title' c, count(*) filter (where title='') e, count(*) filter (where title ~ '^\s+$') w from staging.stg_cpsc_recalls
union all select 'stg_cpsc.description', count(*) filter (where description=''), count(*) filter (where description ~ '^\s+$') from staging.stg_cpsc_recalls
union all select 'stg_nhtsa.desc_defect', count(*) filter (where desc_defect=''), count(*) filter (where desc_defect ~ '^\s+$') from staging.stg_nhtsa_recalls
union all select 'stg_nhtsa.corrective_action', count(*) filter (where corrective_action=''), count(*) filter (where corrective_action ~ '^\s+$') from staging.stg_nhtsa_recalls
union all select 'stg_nhtsa.conequence_defect', count(*) filter (where conequence_defect=''), count(*) filter (where conequence_defect ~ '^\s+$') from staging.stg_nhtsa_recalls
union all select 'stg_nhtsa.fmvss', count(*) filter (where fmvss=''), count(*) filter (where fmvss ~ '^\s+$') from staging.stg_nhtsa_recalls
union all select 'stg_nhtsa.notes', count(*) filter (where notes=''), count(*) filter (where notes ~ '^\s+$') from staging.stg_nhtsa_recalls;

-- ----------------------------------------------------------------------------------
-- stg_usda_classification_enum_cardinality   [enum_domain]   target: staging.stg_usda_fsis_recalls.classification
-- purpose : Confirm the distinct classification value set is exactly the documented {Class I, Class II, Class III, Public Health Alert} with no '' / NULL / out-of-set value (the raw-passthrough column has no nullif guard, so an '' or new value would only be caught here / by the not_null+accepted_values tests).
-- CONFORMS: Exactly these keys present: 'Class I','Class II','Class III','Public Health Alert'. NO '' key, NO NULL key. Any '' / NULL / extra value confirms the raw-passthrough discrepancy and would fail the yml not_null/accepted_values tests.
-- ----------------------------------------------------------------------------------
select classification, count(*) as n
from staging.stg_usda_fsis_recalls
group by classification
order by n desc;

-- ----------------------------------------------------------------------------------
-- stg_uscg_disposition_enum_cardinality   [enum_domain]   target: staging.stg_uscg_recalls.disposition
-- purpose : Confirm lower(nullif(disposition,'')) yields exactly {open, closed} (+ NULL) so the error-severity accepted_values(open,closed) test cannot be tripped by a new source casing/value.
-- CONFORMS: Keys: 'open','closed', and possibly NULL (from '' source). No other value. Any other key would HARD-FAIL the error-severity accepted_values test.
-- ----------------------------------------------------------------------------------
select disposition, count(*) as n
from staging.stg_uscg_recalls
group by disposition
order by n desc;

-- ----------------------------------------------------------------------------------
-- stg_uscg_severity_enum_cardinality   [enum_domain]   target: staging.stg_uscg_recalls.severity
-- purpose : Confirm the CASE-membership severity emits only {H,L,M,S} or NULL (the out-of-set '1' outlier and any other non-{H,L,M,S} must be NULL, never leaked).
-- CONFORMS: Keys strictly subset of {'H','L','M','S'} plus NULL. NO '1', no lowercase, no '' — the CASE expression nulls everything out-of-set. ~23% NULL expected.
-- ----------------------------------------------------------------------------------
select severity, count(*) as n
from staging.stg_uscg_recalls
group by severity
order by n desc;

-- ----------------------------------------------------------------------------------
-- stg_fda_classification_enum_cardinality   [enum_domain]   target: staging.stg_fda_recalls.center_classification_type_txt
-- purpose : Confirm the FDA classification staging column carries the RAW source codes {1,2,3,NC} (per stg yml accepted_values) and NOT 'Class I/II/III' — reconciling the input (C) produced_enum mislabel.
-- CONFORMS: Keys in {'1','2','3','NC'} plus NULL (from nullif('')). NO 'Class I'/'Class II'/'Class III' values — the Class-label mapping is a downstream silver transform, not present at staging.
-- ----------------------------------------------------------------------------------
select center_classification_type_txt, count(*) as n
from staging.stg_fda_recalls
group by center_classification_type_txt
order by n desc;

-- ----------------------------------------------------------------------------------
-- staging_recall_grain_uniqueness   [grain]   target: staging single-key latest-version models
-- purpose : Confirm each single-key latest-version staging model is row-unique on its declared grain key (the row_number/distinct-on rn=1 collapse). Matches the yml not_null+unique tests.
-- CONFORMS: rows = keys for every model (count(*) = count(distinct grain key)). Any rows > keys means the latest-version dedup is not collapsing to one row per key and the unique test would fail.
-- ----------------------------------------------------------------------------------
select 'stg_cpsc_recalls' t, count(*) rows, count(distinct source_recall_id) keys from staging.stg_cpsc_recalls
union all select 'stg_fda_recalls', count(*), count(distinct source_recall_id) from staging.stg_fda_recalls
union all select 'stg_usda_fsis_recalls', count(*), count(distinct source_recall_id) from staging.stg_usda_fsis_recalls
union all select 'stg_uscg_recalls', count(*), count(distinct source_recall_id) from staging.stg_uscg_recalls
union all select 'stg_uscg_manufacturers', count(*), count(distinct source_recall_id) from staging.stg_uscg_manufacturers
union all select 'stg_uscg_manufacturer_details', count(*), count(distinct source_recall_id) from staging.stg_uscg_manufacturer_details
union all select 'stg_usda_fsis_establishments', count(*), count(distinct source_recall_id) from staging.stg_usda_fsis_establishments;

-- ----------------------------------------------------------------------------------
-- stg_fda_press_releases_grain_uniqueness   [grain]   target: staging.stg_fda_press_releases
-- purpose : Confirm stg_fda_press_releases is unique on its composite latest-version grain (source_recall_id, press_release_url) per the rn=1 partition.
-- CONFORMS: rows = keys: one row per (source_recall_id, press_release_url). The yml has no unique test here, so this verifies the grain claim directly.
-- ----------------------------------------------------------------------------------
select count(*) as rows,
       count(distinct (source_recall_id, press_release_url)) as keys
from staging.stg_fda_press_releases;

-- ----------------------------------------------------------------------------------
-- stg_nhtsa_current_7tuple_uniqueness   [grain]   target: staging.stg_nhtsa_recalls_current.recall_product_id
-- purpose : Confirm the 7-tuple distinct-on collapse yields a row-unique recall_product_id (the single strongest guard that the v1.5 anchor recipe is sound, per the yml not_null+unique test).
-- CONFORMS: rows = keys and null_keys = 0: recall_product_id is unique and not_null at the 7-tuple grain. rows here should be <= the 11-tuple stg_nhtsa_recalls row count (further collapse).
-- ----------------------------------------------------------------------------------
select count(*) as rows,
       count(distinct recall_product_id) as keys,
       count(*) filter (where recall_product_id is null) as null_keys
from staging.stg_nhtsa_recalls_current;

-- ----------------------------------------------------------------------------------
-- stg_nhtsa_11tuple_vs_current_collapse   [grain]   target: staging.stg_nhtsa_recalls vs staging.stg_nhtsa_recalls_current
-- purpose : Verify the 7-tuple current view collapses STRICTLY further than the 11-tuple staging input (rows_current <= rows_11tuple), consistent with ADR 0034's ~0.38% residual collapse and confirming the demoted-field latest-wins behavior.
-- CONFORMS: rows_7tuple <= rows_11tuple, with a small residual (~0.38% per ADR 0034). rows_7tuple > rows_11tuple would be impossible (a further DISTINCT ON cannot add rows) and would indicate a logic error.
-- ----------------------------------------------------------------------------------
select
  (select count(*) from staging.stg_nhtsa_recalls) as rows_11tuple,
  (select count(*) from staging.stg_nhtsa_recalls_current) as rows_7tuple;

-- ----------------------------------------------------------------------------------
-- stg_uscg_units_integer_range_sanity   [range_sanity]   target: staging.stg_uscg_recalls.units
-- purpose : Confirm the units integer cast (case when units ~ '^[0-9]+$' then units::integer end) produces only non-negative integers or NULL — no negative values (regex excludes signs) and non-numeric source values null out.
-- CONFORMS: negative_units = 0 (the ^[0-9]+$ regex cannot match a sign); min_units >= 0; NULLs present for non-numeric / '' / 'N/A' source rows. A negative would indicate the cast logic changed.
-- ----------------------------------------------------------------------------------
select
  count(*) as total,
  count(units) as non_null_units,
  count(*) filter (where units < 0) as negative_units,
  min(units) as min_units, max(units) as max_units
from staging.stg_uscg_recalls;

-- ----------------------------------------------------------------------------------
-- stg_model_year_sentinel_strip   [normalization]   target: staging.stg_uscg_recalls.model_year / staging.stg_nhtsa_recalls.model_year
-- purpose : Confirm the 9999 'unknown' sentinel and '' are stripped to NULL at staging (nullif(nullif(col,''),'9999')) — no surviving '9999' or '' values.
-- CONFORMS: n_9999 = 0 and n_empty = 0 for both: the sentinel and empty string are nulled. Any survivor indicates the nullif chain regressed.
-- ----------------------------------------------------------------------------------
select 'uscg' src,
       count(*) filter (where model_year = '9999') as n_9999,
       count(*) filter (where model_year = '') as n_empty
from staging.stg_uscg_recalls
union all
select 'nhtsa',
       count(*) filter (where model_year = '9999'),
       count(*) filter (where model_year = '')
from staging.stg_nhtsa_recalls;

-- ----------------------------------------------------------------------------------
-- stg_usda_establishments_false_sentinel_strip   [normalization]   target: staging.stg_usda_fsis_establishments.county / .geolocation
-- purpose : Confirm the JSON-boolean 'false' sentinel is stripped to NULL on county and geolocation (nullif(col,'false')) and surface whether any literal '' survives (the gap: only 'false' is nulled, not '').
-- CONFORMS: county_false = 0 and geo_false = 0 (sentinel stripped). county_empty / geo_empty SHOULD be 0 if '' never occurs; any > 0 confirms the asymmetric-normalization discrepancy (county/geolocation null 'false' but not '').
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where county = 'false') as county_false,
  count(*) filter (where county = '') as county_empty,
  count(*) filter (where geolocation = 'false') as geo_false,
  count(*) filter (where geolocation = '') as geo_empty
from staging.stg_usda_fsis_establishments;

-- ----------------------------------------------------------------------------------
-- stg_usda_establishment_residual_html_entities   [normalization]   target: staging.stg_usda_fsis_recalls.establishment
-- purpose : Confirm the 2-entity HTML decode (&#039;, &amp;) leaves no residual decoded-target entities, and surface any OTHER &...; entities that survive (the narrow-entity-surface limitation).
-- CONFORMS: residual_apos = 0 and residual_amp = 0 (the two decoded entities are gone). any_entity = 0 ideally; any_entity > 0 surfaces un-decoded entities (e.g. &quot;) depressing the establishment match rate — the documented narrow-surface limitation.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where establishment like '%&#039;%') as residual_apos,
  count(*) filter (where establishment like '%&amp;%') as residual_amp,
  count(*) filter (where establishment ~ '&[a-zA-Z#0-9]+;') as any_entity
from staging.stg_usda_fsis_recalls;

-- ----------------------------------------------------------------------------------
-- stg_usda_recalls_langcode_filter_and_trim   [grain]   target: staging.stg_usda_fsis_recalls
-- purpose : Confirm the staging model emits ONLY English rows (langcode='English' filter, sql:87) and that source_recall_id is trimmed (no leading/trailing whitespace, Finding R) — i.e. the dedup grain is clean.
-- CONFORMS: rows = keys (unique English-only grain); untrimmed_ids = 0 (trim applied in both partition and projection); empty_ids = 0. Confirms langcode filter + Finding-R trim.
-- ----------------------------------------------------------------------------------
select
  count(*) as rows,
  count(distinct source_recall_id) as keys,
  count(*) filter (where source_recall_id <> trim(source_recall_id)) as untrimmed_ids,
  count(*) filter (where source_recall_id = '') as empty_ids
from staging.stg_usda_fsis_recalls;

-- ----------------------------------------------------------------------------------
-- stg_usda_status_regulated_est_meaningful_empty   [enum_domain]   target: staging.stg_usda_fsis_establishments.status_regulated_est
-- purpose : Confirm status_regulated_est carries ONLY the two documented values {'', 'Inactive'} — '' is the MEANINGFUL active value (must NOT be normalized to NULL); any third value or NULL would fail the accepted_values('',Inactive) test.
-- CONFORMS: Exactly two keys: '' (~90%, = active) and 'Inactive' (~10%). NO NULL (raw passthrough, not nulled) and no third value. This is the guardrail that '' stays meaningful — an empty-string sweep must allowlist this column.
-- ----------------------------------------------------------------------------------
select status_regulated_est, count(*) as n
from staging.stg_usda_fsis_establishments
group by status_regulated_est
order by n desc;

-- ----------------------------------------------------------------------------------
-- staging_notnull_claimed_columns   [nullability]   target: staging not-null-claimed columns
-- purpose : Count NULLs on staging columns the yml asserts not_null (source_recall_id, announced_at/published_at where claimed, title, classification, content_hash, recall_product_id) to confirm the not_null contracts hold.
-- CONFORMS: All counts = 0. Any non-zero on a not_null-claimed staging column means the contract is violated (esp. stg_usda classification, the raw-passthrough column that has no nullif guard but a not_null test).
-- ----------------------------------------------------------------------------------
select 'stg_cpsc.announced_at' c, count(*) filter (where announced_at is null) n from staging.stg_cpsc_recalls
union all select 'stg_cpsc.published_at', count(*) filter (where published_at is null) from staging.stg_cpsc_recalls
union all select 'stg_usda.announced_at', count(*) filter (where announced_at is null) from staging.stg_usda_fsis_recalls
union all select 'stg_usda.title', count(*) filter (where title is null) from staging.stg_usda_fsis_recalls
union all select 'stg_usda.classification', count(*) filter (where classification is null) from staging.stg_usda_fsis_recalls
union all select 'stg_nhtsa_current.recall_product_id', count(*) filter (where recall_product_id is null) from staging.stg_nhtsa_recalls_current
union all select 'stg_cpsc.source_recall_id', count(*) filter (where source_recall_id is null) from staging.stg_cpsc_recalls;
