-- Silver/Gold Provenance Audit — Silver — recall_event + children
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- SCHEMAS: ALL staging views / silver tables / gold marts+facts / dbt seeds live in schema "public"
--   (dbt generate_schema_name -> target.schema = public; only the SCD-2 snapshots set a custom schema).
--   SCD-2 snapshots live in "silver_snapshots". seeds: public.us_state_abbr, public.country_iso.
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit_2026_w25.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- silver_event_text_types   [type]   target: public.recall_event, public.recall_event_history, public.recall_event_firm, public.recall_event_establishment_resolution, public.recall_event_press_release
-- purpose : Information_schema-driven type sweep for every column in this group: confirm produced data_type + is_nullable matches the produced shapes (text/timestamptz/boolean/jsonb/integer/bigint). Cannot silently miss a column.
-- CONFORMS: recall_event_id/source/source_recall_id/title/recall_reason/classification/lifecycle_status/risk_level/etc = text; announced_at/published_at/first_posted_at/terminated_at/campaign_*/last_editorial_date/owner_notified_at/changed_at/issued_at = timestamp with time zone; is_active/do_not_drive/park_outside/related_to_outbreak/archived/cold_storage_flag = boolean; hazards/remedies/.../source_payload_raw/reason_category_tokens = jsonb; terminated_year = integer; n_candidates = bigint. source/source_recall_id/recall_event_id/role/field_name/changed_at = is_nullable='NO'; announced_at/classification/risk_level/terminated_year/etc = is_nullable='YES'.
-- ----------------------------------------------------------------------------------
select c.table_name, c.column_name, c.data_type, c.is_nullable
from information_schema.columns c
where c.table_schema = 'public'
  and c.table_name in ('recall_event','recall_event_history','recall_event_firm','recall_event_establishment_resolution','recall_event_press_release')
order by c.table_name, c.ordinal_position;

-- ----------------------------------------------------------------------------------
-- recall_event_source_enum   [enum_domain]   target: public.recall_event.source
-- purpose : Confirm source is the closed UPPERCASE 5-value enum (ADR 0042 load-bearing for the API md5).
-- CONFORMS: Exactly {CPSC, FDA, USDA, NHTSA, USCG}, all uppercase, no other/lowercase/empty value, no NULL.
-- ----------------------------------------------------------------------------------
select source, count(*) as n from public.recall_event group by source order by source;

-- ----------------------------------------------------------------------------------
-- recall_event_classification_enum   [enum_domain]   target: public.recall_event.classification
-- purpose : Enumerate the PRODUCED classification domain per source vs the contract. Settles the FDA '1/2/3/NC' vs documented 'Class I/II/III' mismatch and confirms CPSC/NHTSA are NULL.
-- CONFORMS: FDA classification in {1,2,3,NC} (this would CONFIRM the doc mismatch — docs/ADR 0042 claim Class I/II/III); USDA in {Class I,Class II,Class III}; USCG in {H,L,M,S}; CPSC and NHTSA classification IS NULL (no non-null rows). Any value outside these per-source sets is drift.
-- ----------------------------------------------------------------------------------
select source, classification, count(*) as n
from public.recall_event
group by source, classification
order by source, classification;

-- ----------------------------------------------------------------------------------
-- recall_event_lifecycle_status_enum   [enum_domain]   target: public.recall_event.lifecycle_status
-- purpose : Enumerate produced lifecycle_status per source (no silver accepted_values exists).
-- CONFORMS: FDA in {Ongoing,Terminated,Completed}; USDA in {Active Recall,Closed Recall,Public Health Alert}; USCG in {Open,Closed} (initcap'd); CPSC and NHTSA NULL. No empty string, no unexpected value.
-- ----------------------------------------------------------------------------------
select source, lifecycle_status, count(*) as n
from public.recall_event
group by source, lifecycle_status
order by source, lifecycle_status;

-- ----------------------------------------------------------------------------------
-- recall_event_distribution_scope_enum   [enum_domain]   target: public.recall_event.distribution_scope
-- purpose : Positive control: distribution_scope must be the closed NOT-NULL 4-value enum (matches macro + _silver.yml + _gold.yml).
-- CONFORMS: Exactly {Nationwide, International, Regional, Unspecified}; zero NULLs; no other value.
-- ----------------------------------------------------------------------------------
select distribution_scope, count(*) as n
from public.recall_event
group by distribution_scope
order by distribution_scope;

-- ----------------------------------------------------------------------------------
-- recall_event_risk_level_enum   [enum_domain]   target: public.recall_event.risk_level
-- purpose : Confirm risk_level is USDA-only and the closed 4-value derived domain.
-- CONFORMS: Non-null risk_level only for source='USDA', in {High - Class I, Low - Class II, Marginal - Class III, Public Health Alert}; CPSC/FDA/NHTSA/USCG risk_level IS NULL.
-- ----------------------------------------------------------------------------------
select source, risk_level, count(*) as n
from public.recall_event
group by source, risk_level
order by source, risk_level;

-- ----------------------------------------------------------------------------------
-- recall_event_initiated_by_enum   [enum_domain]   target: public.recall_event.initiated_by
-- purpose : Confirm initiated_by closed derived domain {firm, agency} (ADR 0036 D4).
-- CONFORMS: initiated_by in {firm, agency, NULL}; non-null only for FDA and NHTSA; CPSC/USDA/USCG NULL. No value outside {firm,agency}.
-- ----------------------------------------------------------------------------------
select source, initiated_by, count(*) as n
from public.recall_event
group by source, initiated_by
order by source, initiated_by;

-- ----------------------------------------------------------------------------------
-- recall_event_is_active_tristate   [nullability]   target: public.recall_event.is_active
-- purpose : Confirm is_active tri-state: NULL for CPSC/NHTSA; true/false populated for FDA/USDA/USCG (ADR 0042).
-- CONFORMS: CPSC and NHTSA: is_active IS NULL for every row. FDA/USDA/USCG: predominantly true/false (a small NULL tail allowed only where the CASE has no matching branch). No CPSC/NHTSA non-null.
-- ----------------------------------------------------------------------------------
select source, is_active, count(*) as n
from public.recall_event
group by source, is_active
order by source, is_active;

-- ----------------------------------------------------------------------------------
-- recall_event_notnull_keys   [nullability]   target: public.recall_event
-- purpose : Count NULLs on the not-null-claimed columns (recall_event_id, source, source_recall_id, published_at, distribution_scope).
-- CONFORMS: All five counts = 0 (these are the hard not-null contract columns; announced_at is intentionally excluded — it is nullable by design).
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where recall_event_id is null)    as null_event_id,
  count(*) filter (where source is null)             as null_source,
  count(*) filter (where source_recall_id is null)   as null_source_recall_id,
  count(*) filter (where published_at is null)       as null_published_at,
  count(*) filter (where distribution_scope is null) as null_distribution_scope
from public.recall_event;

-- ----------------------------------------------------------------------------------
-- recall_event_announced_at_nullable_watch   [nullability]   target: public.recall_event.announced_at
-- purpose : announced_at is nullable by design (~20 FDA baseline); confirm the NULL set is bounded and FDA-concentrated (severity=warn watch-list).
-- CONFORMS: USCG = 0 (model filters announced_at IS NOT NULL). FDA null count near the ~20 baseline (materially larger = investigate). CPSC/USDA/NHTSA near 0 (passthroughs of always-populated source dates).
-- ----------------------------------------------------------------------------------
select source, count(*) filter (where announced_at is null) as n_null_announced
from public.recall_event
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- silver_event_empty_string_sweep   [empty_string]   target: public.recall_event, public.recall_event_firm, public.recall_event_establishment_resolution, public.recall_event_press_release
-- purpose : Extend the existing empty_string_freetext_audit DO-block to THIS group's text columns. Per (table,column[,source]) count exact '' and whitespace-only. EXCLUDES recall_event_history (old_value/new_value '' is BY DESIGN). recall_event has a source column (group by source); recall_event_firm/resolution/press_release have no source column (sweep ungrouped).
-- CONFORMS: recall_event: 0 empties/whitespace for the already-fixed columns (title, recall_reason, corrective_action, consequence_of_defect, notes, mfgcampno, fmvss) across all sources. Watch columns (USCG recall_reason coalesce, USDA distribution_states/firm_contact_block_text, CPSC consumer_contact, USCG firm_contact_person, FDA classification/recall_reason passthroughs) should ALSO be 0 if assert_no_blank_freetext_serving + staging nullif hold; any non-zero cell is an unfixed leak. recall_event_press_release.release_type/url = 0; recall_event_firm/resolution text columns = 0.
-- VERIFY-NOTE: Original SQL is illustrative pseudo-code referencing a non-existent `t.col` lateral alias and cannot execute as-is. Replaced with a concrete cross-join lateral VALUES approach covering the key free-text columns. For the other tables (recall_event_firm, recall_event_establishment_resolution, recall_event_press_release) run analogous queries against their text columns.
-- ----------------------------------------------------------------------------------
-- Corrected: use the existing DO-block pattern from scripts/sql/cross_source/empty_string_freetext_audit.sql,
-- extended to cover these tables. The original SQL is illustrative pseudo-code that cannot execute as written
-- (it references a non-existent lateral alias 't.col' and the information_schema join with a dynamic column
-- name is not executable in plain SQL without PL/pgSQL). Provide a concrete executable sweep for one table:
select
  column_name,
  count(*) filter (where val = '')              as n_empty,
  count(*) filter (where val <> '' and val ~ '^\s+$') as n_ws,
  count(*)                                      as n_total
from public.recall_event
cross join lateral (
  values
    ('title',                   title),
    ('url',                     url),
    ('recall_reason',           recall_reason),
    ('consumer_contact',        consumer_contact),
    ('firm_contact_block_text', firm_contact_block_text),
    ('firm_contact_person',     firm_contact_person),
    ('distribution_states',     distribution_states),
    ('corrective_action',       corrective_action),
    ('consequence_of_defect',   consequence_of_defect),
    ('notes',                   notes),
    ('mfgcampno',               mfgcampno),
    ('fmvss',                   fmvss)
) as v(column_name, val)
group by column_name
order by column_name;

-- ----------------------------------------------------------------------------------
-- recall_event_grain_uniqueness   [grain]   target: public.recall_event
-- purpose : Confirm one row per (source, source_recall_id) and per recall_event_id (PK).
-- CONFORMS: n_rows = n_event_id = n_source_pair (md5(source|source_recall_id) is 1:1 with the natural key; FDA/NHTSA DISTINCT ON collapse already applied).
-- ----------------------------------------------------------------------------------
select
  count(*) as n_rows,
  count(distinct recall_event_id) as n_event_id,
  count(distinct (source, source_recall_id)) as n_source_pair
from public.recall_event;

-- ----------------------------------------------------------------------------------
-- recall_event_firm_grain_and_role_enum   [grain]   target: public.recall_event_firm
-- purpose : Confirm composite uniqueness (recall_event_id, firm_id, role) and the closed 5-value role enum.
-- CONFORMS: n_rows = n_distinct_triples (composite PK holds). role exactly in {manufacturer, importer, distributor, establishment, filer}; no 'retailer', no NULL, no empty.
-- VERIFY-NOTE: Original SQL contained two separate SELECT statements in a single string which is not executable as a single query in most clients. Split into two statements. The first uses count(distinct (recall_event_id, firm_id, role)) which works in PostgreSQL for a row-constructor distinct count. Confirmed column names recall_event_id, firm_id, role exist in recall_event_firm.sql output.
-- ----------------------------------------------------------------------------------
select
  count(*) as n_rows,
  count(distinct (recall_event_id, firm_id, role)) as n_distinct_triples,
  count(distinct role) as n_distinct_roles
from public.recall_event_firm;

-- Run separately for role distribution:
select role, count(*) as n from public.recall_event_firm group by role order by role;

-- ----------------------------------------------------------------------------------
-- recall_event_firm_match_confidence_enum   [enum_domain]   target: public.recall_event_firm.match_confidence
-- purpose : Enumerate produced match_confidence against the 17-value error-severity accepted_values; catch any crosswalk-injected label (e.g. rapidfuzz_high) outside the set.
-- CONFORMS: Every value within {exact_name, geo_suffix_strip_exact, dba_extract_exact, usda_unambiguous, usda_product_items_extract, usda_state_match, usda_processing_match, usda_multi_signal, usda_ambiguous_null, uscg_mic_unambiguous, uscg_mic_time_sensitive_unresolved, uscg_mic_build_date_resolved, fei_exact, name_variant_exact, name_typo_high, rapidfuzz_rollup, singleton}. Any other label (e.g. 'rapidfuzz_high') = a crosswalk vocabulary mismatch that would trip the error-severity test.
-- ----------------------------------------------------------------------------------
select match_confidence, count(*) as n
from public.recall_event_firm
group by match_confidence
order by n desc;

-- ----------------------------------------------------------------------------------
-- recall_event_firm_fk_integrity   [grain]   target: public.recall_event_firm
-- purpose : Confirm relationships hold: every recall_event_id and firm_id resolves (no orphans — the 1549-orphan USCG lockstep regression must read 0).
-- CONFORMS: orphan_events = 0 and orphan_firms = 0 (firm.sql / recall_event_firm.sql lockstep preserved).
-- ----------------------------------------------------------------------------------
select
  (select count(*)
     from public.recall_event_firm b
     left join public.recall_event e on e.recall_event_id = b.recall_event_id
     where e.recall_event_id is null) as orphan_events,
  (select count(*)
     from public.recall_event_firm b
     left join public.firm f on f.firm_id = b.firm_id
     where f.firm_id is null) as orphan_firms;

-- ----------------------------------------------------------------------------------
-- establishment_resolution_grain_and_enum   [grain]   target: public.recall_event_establishment_resolution
-- purpose : Confirm one row per USDA recall_event_id (unique PK) and the 4-value match_confidence enum; confirm n_candidates>=1 and establishment_number NULL only when usda_ambiguous_null.
-- CONFORMS: n_rows = n_distinct_event (unique PK); min_candidates >= 1; null_num_non_ambiguous = 0 (establishment_number is NULL only for usda_ambiguous_null); match_confidence exactly in {usda_unambiguous, usda_product_items_extract, usda_state_match, usda_ambiguous_null}.
-- VERIFY-NOTE: Original SQL contains two separate SELECT statements. Split into two. n_candidates is a real produced column (confirmed at recall_event_establishment_resolution.sql:127 via the n_cand CTE). Both queries are valid read-only SQL.
-- ----------------------------------------------------------------------------------
select
  count(*) as n_rows,
  count(distinct recall_event_id) as n_distinct_event,
  min(n_candidates) as min_candidates,
  count(*) filter (where establishment_number is null and match_confidence <> 'usda_ambiguous_null') as null_num_non_ambiguous
from public.recall_event_establishment_resolution;

-- Run separately for match_confidence distribution:
select match_confidence, count(*) as n
from public.recall_event_establishment_resolution
group by match_confidence
order by match_confidence;

-- ----------------------------------------------------------------------------------
-- recall_event_history_grain_and_field_enum   [grain]   target: public.recall_event_history
-- purpose : Confirm the documented 5-col composite uniqueness (source, source_recall_id, langcode, field_name, changed_at) and the closed field_name enum.
-- CONFORMS: n_rows = n_distinct_key (composite uniqueness holds; langcode NULL folded to a sentinel for the distinct count). field_name exactly in {recall_reason, classification, lifecycle_status, title, terminated_at}.
-- VERIFY-NOTE: Original SQL contains two separate SELECT statements. Split into two. Note: count(distinct row_constructor) on a 5-tuple may behave unexpectedly in some PostgreSQL versions; an alternative is to use a subquery: (select count(*) from (select distinct source, source_recall_id, coalesce(langcode,'<null>'), field_name, changed_at from silver.recall_event_history) d) as n_distinct_key. Both columns referenced (langcode, field_name, changed_at, changed_at) are confirmed in recall_event_history.sql output at lines 209-216.
-- ----------------------------------------------------------------------------------
select
  count(*) as n_rows,
  count(distinct (source, source_recall_id, coalesce(langcode, '<null>'), field_name, changed_at)) as n_distinct_key
from public.recall_event_history;

-- Run separately for field_name distribution:
select field_name, count(*) as n from public.recall_event_history group by field_name order by field_name;

-- ----------------------------------------------------------------------------------
-- recall_event_history_change_type_enum   [enum_domain]   target: public.recall_event_history.change_type
-- purpose : Confirm change_type is the residual 3-value set (rebaseline runs filtered out per ADR 0027/0028).
-- CONFORMS: change_type in {routine, historical_seed, etag_audit} only; NO schema_rebaseline or hash_helper_rebaseline rows (excluded by the model WHERE).
-- ----------------------------------------------------------------------------------
select change_type, count(*) as n
from public.recall_event_history
group by change_type
order by change_type;

-- ----------------------------------------------------------------------------------
-- recall_event_terminated_year_source_coverage   [range_sanity]   target: public.recall_event.terminated_year
-- purpose : Settle the doc/code disagreement: data_schemas.md says terminated_year is USDA+USCG only, but the model populates FDA too. Check per-source population + value range.
-- CONFORMS: If the code is authoritative: FDA, USDA, USCG all have non-null terminated_year (doc is stale). CPSC/NHTSA n_nonnull = 0. min_yr >= 1940 and max_yr <= current_year+1 (no garbage years). A non-zero FDA n_nonnull confirms the data_schemas.md 'USDA + USCG only' claim is wrong.
-- ----------------------------------------------------------------------------------
select source,
  count(*) filter (where terminated_year is not null) as n_nonnull,
  min(terminated_year) as min_yr,
  max(terminated_year) as max_yr
from public.recall_event
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- recall_event_date_range_sanity   [range_sanity]   target: public.recall_event.published_at, public.recall_event.announced_at
-- purpose : Date sanity per ADR 0015 (assert_recall_event_date_sanity floor 1940, not future) on the served dates.
-- CONFORMS: pub_before_1940 = 0, pub_future = 0, ann_before_1940 = 0 (FDA >=1940 guard), ann_future = 0. Any non-zero indicates a date-sanity regression.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where published_at < '1940-01-01') as pub_before_1940,
  count(*) filter (where published_at > now()) as pub_future,
  count(*) filter (where announced_at is not null and announced_at < '1940-01-01') as ann_before_1940,
  count(*) filter (where announced_at is not null and announced_at > now()) as ann_future
from public.recall_event;
