-- Silver/Gold Provenance Audit — Silver — recall_product + distribution + lifecycle
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- SCHEMAS: ALL staging views / silver tables / gold marts+facts / dbt seeds live in schema "public"
--   (dbt generate_schema_name -> target.schema = public; only the SCD-2 snapshots set a custom schema).
--   SCD-2 snapshots live in "silver_snapshots". seeds: public.us_state_abbr, public.country_iso.
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit_2026_w25.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- recall_product_column_types   [type]   target: public.recall_product
-- purpose : Verify produced column types match the documented/derived shapes: text keys, integer unit_count, jsonb source_specific_attrs/processing_categories, numeric quantity_value, text[] none here.
-- CONFORMS: recall_product_id/recall_event_id/source/source_recall_id/product_name/product_description/model/type/category_id/number_of_units/model_year/hin/label_artifact_name/distribution_list_artifact_name/upc = text; unit_count = integer; source_specific_attrs + processing_categories = jsonb; quantity_value = numeric; quantity_unit/quantity_category/quantity_basis = text. No unexpected columns.
-- ----------------------------------------------------------------------------------
select column_name, data_type, is_nullable from information_schema.columns where table_schema = 'public' and table_name = 'recall_product' order by ordinal_position;

-- ----------------------------------------------------------------------------------
-- recall_product_freetext_empty_string_sweep   [empty_string]   target: public.recall_product
-- purpose : Confirm the already-fixed free-text columns carry zero '' (guarded) AND the UNWRAPPED passthrough columns (source_recall_id, model_year, hin, label_artifact_name, distribution_list_artifact_name) are also '' / whitespace-free as the header claims 'null-clean upstream'. Settles the ambiguous empty_string_risk flags.
-- CONFORMS: All rows n_empty = 0 and n_ws = 0. The guarded columns (product_name/description/model/type/category_id) are enforced by assert_no_blank_freetext_serving; the unwrapped passthroughs (model_year/hin/artifact names/source_recall_id) should ALSO be 0 because staging nullif's them upstream. Any non-zero on the passthroughs confirms the missing-guard risk is live.
-- ----------------------------------------------------------------------------------
select 'product_name' col, count(*) filter (where product_name = '') n_empty, count(*) filter (where product_name <> '' and product_name ~ '^\s+$') n_ws from recall_product union all select 'product_description', count(*) filter (where product_description=''), count(*) filter (where product_description<>'' and product_description ~ '^\s+$') from recall_product union all select 'model', count(*) filter (where model=''), count(*) filter (where model<>'' and model ~ '^\s+$') from recall_product union all select 'type', count(*) filter (where type=''), count(*) filter (where type<>'' and type ~ '^\s+$') from recall_product union all select 'category_id', count(*) filter (where category_id=''), count(*) filter (where category_id<>'' and category_id ~ '^\s+$') from recall_product union all select 'number_of_units', count(*) filter (where number_of_units=''), count(*) filter (where number_of_units<>'' and number_of_units ~ '^\s+$') from recall_product union all select 'model_year', count(*) filter (where model_year=''), count(*) filter (where model_year<>'' and model_year ~ '^\s+$') from recall_product union all select 'hin', count(*) filter (where hin=''), count(*) filter (where hin<>'' and hin ~ '^\s+$') from recall_product union all select 'label_artifact_name', count(*) filter (where label_artifact_name=''), count(*) filter (where label_artifact_name<>'' and label_artifact_name ~ '^\s+$') from recall_product union all select 'distribution_list_artifact_name', count(*) filter (where distribution_list_artifact_name=''), count(*) filter (where distribution_list_artifact_name<>'' and distribution_list_artifact_name ~ '^\s+$') from recall_product union all select 'source_recall_id', count(*) filter (where source_recall_id=''), count(*) filter (where source_recall_id<>'' and source_recall_id ~ '^\s+$') from recall_product;

-- ----------------------------------------------------------------------------------
-- recall_product_source_enum   [enum_domain]   target: public.recall_product
-- purpose : Confirm source is the closed UPPERCASE set with no stray/lowercase value.
-- CONFORMS: Exactly {CPSC, FDA, USDA, NHTSA, USCG}, all uppercase, no NULL, no other values.
-- ----------------------------------------------------------------------------------
select source, count(*) from recall_product group by source order by source;

-- ----------------------------------------------------------------------------------
-- recall_product_id_grain_uniqueness   [grain]   target: public.recall_product
-- purpose : Confirm recall_product_id is row-unique across the five-source union (API keyset cursor contract, ADR 0042) and not_null.
-- CONFORMS: n_rows = n_distinct_id (no cross-source md5 collision) and n_null_id = 0.
-- ----------------------------------------------------------------------------------
select count(*) as n_rows, count(distinct recall_product_id) as n_distinct_id, count(*) filter (where recall_product_id is null) as n_null_id from recall_product;

-- ----------------------------------------------------------------------------------
-- recall_product_fk_integrity   [grain]   target: public.recall_product
-- purpose : Confirm every recall_product.recall_event_id resolves to a recall_event (FK relationship), and USDA/USCG are 1:1 (recall_product_id = recall_event_id).
-- CONFORMS: orphan_products = 0 (FK holds) and usda_uscg_not_1to1 = 0 (USDA/USCG one product per recall).
-- ----------------------------------------------------------------------------------
select (select count(*) from recall_product rp left join recall_event re on re.recall_event_id = rp.recall_event_id where re.recall_event_id is null) as orphan_products, (select count(*) from recall_product where source in ('USDA','USCG') and recall_product_id <> recall_event_id) as usda_uscg_not_1to1;

-- ----------------------------------------------------------------------------------
-- recall_product_unit_count_source_distribution   [nullability]   target: public.recall_product
-- purpose : Confirm unit_count is integer-typed and populated only for NHTSA/USCG (NULL by construction for CPSC/FDA/USDA), matching the produced shape.
-- CONFORMS: CPSC/FDA/USDA: non_null_unit_count = 0. NHTSA/USCG: non_null_unit_count > 0 (numeric potaff / units). negative_unit_count = 0 for all sources (sanity).
-- ----------------------------------------------------------------------------------
select source, count(*) total, count(unit_count) non_null_unit_count, count(*) filter (where unit_count < 0) negative_unit_count from recall_product group by source order by source;

-- ----------------------------------------------------------------------------------
-- recall_product_quantity_enum_domains   [enum_domain]   target: public.recall_product
-- purpose : Confirm quantity_category in {count,weight,volume,grouping}+NULL and quantity_basis in {per_product,total_all_products,unknown}+NULL.
-- CONFORMS: category values subset of {count,weight,volume,grouping,<NULL>}; basis values subset of {per_product,total_all_products,unknown,<NULL>}. No value outside these domains.
-- ----------------------------------------------------------------------------------
select 'category' k, coalesce(quantity_category,'<NULL>') v, count(*) from recall_product group by quantity_category union all select 'basis', coalesce(quantity_basis,'<NULL>'), count(*) from recall_product group by quantity_basis order by k, v;

-- ----------------------------------------------------------------------------------
-- recall_product_history_grain   [grain]   target: public.recall_product_history
-- purpose : Confirm recall_product_history grain: dbt_scd_id is unique (one per version), recall_product_id repeats across versions (NOT unique here), is_current is true/false non-null.
-- CONFORMS: n_rows = n_scd_id (dbt_scd_id unique); n_product_id <= n_rows (repeats across versions allowed); n_null_is_current = 0; n_is_current_mismatch = 0 (is_current exactly equals dbt_valid_to is null); n_current_versions = count of current rows = distinct current recall_product_ids.
-- ----------------------------------------------------------------------------------
select count(*) n_rows, count(distinct dbt_scd_id) n_scd_id, count(distinct recall_product_id) n_product_id, count(*) filter (where is_current is null) n_null_is_current, count(*) filter (where dbt_valid_to is null) n_current_versions, count(*) filter (where is_current <> (dbt_valid_to is null)) n_is_current_mismatch from recall_product_history;

-- ----------------------------------------------------------------------------------
-- recall_product_history_intentional_empty_string   [empty_string]   target: public.recall_product_history
-- purpose : Document (not fail) that recall_product_history INTENTIONALLY carries '' in its NHTSA passthrough attribute columns (e.g. mfr_comp_desc) — the audit signal. This query records the count so the team confirms the carve-out is real, not a regression of the serving fix.
-- CONFORMS: n_empty MAY be > 0 here (by design — this is the audit/history surface where the ''->value depopulation/population transition is the point). This is NOT a failure; it documents the deliberate exception. Contrast with the served recall_product (recall_product columns must be 0).
-- ----------------------------------------------------------------------------------
select 'mfr_comp_desc' col, count(*) filter (where mfr_comp_desc = '') n_empty from recall_product_history union all select 'mfr_comp_name', count(*) filter (where mfr_comp_name='') from recall_product_history union all select 'fmvss', count(*) filter (where fmvss='') from recall_product_history union all select 'maketxt', count(*) filter (where maketxt='') from recall_product_history;  -- bgman/endman removed: they are timestamptz, cannot hold '' (audited 2026-W25)

-- ----------------------------------------------------------------------------------
-- recall_distribution_area_array_types_and_nonnull   [type]   target: public.recall_distribution_area
-- purpose : Confirm distribution_state_codes / distribution_country_codes are ARRAY (text[]) — settling the database_overview.md scalar-text doc_wrong — and never NULL (coalesced to '{}').
-- CONFORMS: distribution_state_codes/distribution_country_codes: data_type = 'ARRAY', udt_name = '_text' (text[]) — NOT scalar text. n_distribution_states/n_distribution_countries = integer. recall_event_id = text. This confirms database_overview.md:248/250 (scalar text) is wrong.
-- ----------------------------------------------------------------------------------
select column_name, data_type, udt_name from information_schema.columns where table_schema='public' and table_name='recall_distribution_area' and column_name in ('distribution_state_codes','distribution_country_codes','n_distribution_states','n_distribution_countries','recall_event_id') order by column_name;

-- ----------------------------------------------------------------------------------
-- recall_distribution_area_null_array_and_grain   [nullability]   target: public.recall_distribution_area
-- purpose : Confirm arrays are never NULL, recall_event_id is unique/not-null, and the geography invariant holds (every row has >=1 state OR >=1 country).
-- CONFORMS: n_rows = n_distinct (unique recall_event_id); n_null_states = 0 and n_null_countries = 0 (coalesced to '{}'); n_no_geography = 0 (assert_distribution_area_has_geography invariant — every row has at least one state or country).
-- ----------------------------------------------------------------------------------
select count(*) n_rows, count(distinct recall_event_id) n_distinct, count(*) filter (where distribution_state_codes is null) n_null_states, count(*) filter (where distribution_country_codes is null) n_null_countries, count(*) filter (where cardinality(distribution_state_codes)=0 and cardinality(distribution_country_codes)=0) n_no_geography from recall_distribution_area;

-- ----------------------------------------------------------------------------------
-- recall_distribution_area_count_array_consistency   [range_sanity]   target: public.recall_distribution_area
-- purpose : Confirm n_distribution_states = array length of distribution_state_codes and likewise for countries (counts not drifting from arrays).
-- CONFORMS: state_count_mismatch = 0, country_count_mismatch = 0, negative_counts = 0.
-- ----------------------------------------------------------------------------------
select count(*) filter (where n_distribution_states <> cardinality(distribution_state_codes)) as state_count_mismatch, count(*) filter (where n_distribution_countries <> cardinality(distribution_country_codes)) as country_count_mismatch, count(*) filter (where n_distribution_states < 0 or n_distribution_countries < 0) as negative_counts from recall_distribution_area;

-- ----------------------------------------------------------------------------------
-- recall_distribution_area_source_scope   [enum_domain]   target: public.recall_distribution_area
-- purpose : Confirm only FDA + USDA recalls have rows here (the model only parses those two sources' distribution fields).
-- CONFORMS: Only FDA and USDA appear. CPSC/NHTSA/USCG = 0 rows (they carry no distribution field).
-- ----------------------------------------------------------------------------------
select re.source, count(*) from recall_distribution_area rda join recall_event re on re.recall_event_id = rda.recall_event_id group by re.source order by re.source;

-- ----------------------------------------------------------------------------------
-- recall_distribution_country_codes_iso_validity   [enum_domain]   target: public.recall_distribution_area
-- purpose : Confirm every emitted country code is a known ISO alpha-2 in the country_iso seed and US/Georgia are excluded (foreign-only contract).
-- CONFORMS: Zero rows — every country code is in the country_iso seed and 'US' never appears (foreign-only; assert_distribution_country_codes_valid_iso warn-test peer).
-- ----------------------------------------------------------------------------------
select c.code, count(*) from recall_distribution_area rda cross join lateral unnest(rda.distribution_country_codes) as c(code) left join country_iso ci on upper(ci.alpha2) = c.code group by c.code, ci.alpha2 having ci.alpha2 is null or c.code = 'US' order by c.code;

-- ----------------------------------------------------------------------------------
-- recall_lifecycle_grain_and_keys   [grain]   target: public.recall_lifecycle
-- purpose : Confirm 1:1 with recall_event: recall_event_id unique + not_null, and every lifecycle row resolves to a recall_event (driven from ref('recall_event')).
-- CONFORMS: n_rows = n_distinct = n_events (1:1 with recall_event); n_null = 0; n_orphan = 0.
-- ----------------------------------------------------------------------------------
select (select count(*) from recall_lifecycle) n_rows, (select count(distinct recall_event_id) from recall_lifecycle) n_distinct, (select count(*) from recall_lifecycle where recall_event_id is null) n_null, (select count(*) from recall_lifecycle rl left join recall_event re on re.recall_event_id = rl.recall_event_id where re.recall_event_id is null) n_orphan, (select count(*) from recall_event) n_events;

-- ----------------------------------------------------------------------------------
-- recall_lifecycle_tristate_presence_by_source   [nullability]   target: public.recall_lifecycle
-- purpose : Confirm is_currently_active / was_ever_retracted are tri-state: populated for USDA (and NHTSA once a deep-rescan manifest exists), NULL for CPSC/FDA/USCG. Settles the _silver.yml 'USDA-only' vs code 'USDA+NHTSA' doc gap.
-- CONFORMS: CPSC/FDA/USCG: non_null_active = 0 and non_null_retracted = 0 (NULL by design). USDA: > 0 (presence manifest). NHTSA: 0 today (NULL until first deep-rescan banks a manifest) — a non-zero NHTSA count would mean the manifest is now banked and the _silver.yml 'USDA-only' description is stale.
-- ----------------------------------------------------------------------------------
select source, count(*) total, count(is_currently_active) non_null_active, count(was_ever_retracted) non_null_retracted from recall_lifecycle group by source order by source;

-- ----------------------------------------------------------------------------------
-- recall_lifecycle_edit_count_sanity   [range_sanity]   target: public.recall_lifecycle
-- purpose : Sanity-check the bronze-derived lifecycle measures: edit_count >= 1 (count distinct content_hash, 1 = never changed), and first_seen_at <= last_seen_at. Surfaces any LEFT-JOIN miss to bronze_stats (NULLs).
-- CONFORMS: edit_lt_1 = 0 and first_after_last = 0. edit_null / first_seen_null / last_seen_null should be 0 (every recall_event has matching bronze_stats); any non-zero indicates a recall_event present in silver but missing from its bronze source (LEFT JOIN miss) and warrants investigation.
-- ----------------------------------------------------------------------------------
select count(*) filter (where edit_count < 1) edit_lt_1, count(*) filter (where edit_count is null) edit_null, count(*) filter (where first_seen_at is null) first_seen_null, count(*) filter (where last_seen_at is null) last_seen_null, count(*) filter (where first_seen_at > last_seen_at) first_after_last from recall_lifecycle;

-- ----------------------------------------------------------------------------------
-- recall_lifecycle_source_enum   [enum_domain]   target: public.recall_lifecycle
-- purpose : Confirm source passthrough from recall_event is the closed uppercase set.
-- CONFORMS: Exactly {CPSC, FDA, USDA, NHTSA, USCG}, no NULL, no other values.
-- ----------------------------------------------------------------------------------
select source, count(*) from recall_lifecycle group by source order by source;
