-- Silver/Gold Provenance Audit — Silver — firm dimension + sidecars
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- Schemas: staging views = "staging"; silver tables = "silver"; gold = "gold"; dbt seeds = "public" (us_state_abbr, country_iso).
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- firm_sidecar_column_types   [type]   target: silver.firm, silver.firm_fda_attributes, silver.firm_usda_attributes, silver.firm_uscg_attributes, silver.firm_fei_edges, silver.uscg_mic_reassignment_years
-- purpose : Verify produced column data types match the contract/derived shapes (e.g. firm_fei_num bigint, mic text, current_holder_since_year integer, jsonb arrays jsonb, dates timestamptz).
-- CONFORMS: firm.firm_id/normalized_name/canonical_name text; observed_names/observed_company_ids/alternate_names jsonb. firm_fda_attributes.firm_fei_num bigint, firm_surviving_fei bigint, address/name cols text. firm_usda_attributes.establishment_id text, latest_mpi_active_date/grant_date timestamptz, activities/dbas jsonb. firm_uscg_attributes.mic text, mic_has_prior_holder/mic_oob_recycled/mic_renamed_not_recycled boolean, prior_holders jsonb, in_business/out_of_business/date_modified timestamptz. uscg_mic_reassignment_years.mic text, current_holder_since_year integer, reassignment_years jsonb. firm_fei_edges all text.
-- ----------------------------------------------------------------------------------
select table_name, column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'silver'
  and table_name in ('firm','firm_fda_attributes','firm_usda_attributes','firm_uscg_attributes','firm_fei_edges','uscg_mic_reassignment_years')
order by table_name, ordinal_position;

-- ----------------------------------------------------------------------------------
-- firm_usda_sidecar_emptystring_leak   [empty_string]   target: silver.firm_usda_attributes
-- purpose : Empirically confirm the ADR 0027 empty-string leak on the RAW-passthrough columns (establishment_name, city, state, zip) and confirm the nullif'd columns are clean. THIS is the central finding.
-- CONFORMS: In a CONFORMING (fixed) database all counts = 0. TODAY (pre-fix) name_empty / city_empty / state_empty / zip_empty may be > 0 (the leak); address_empty must be 0 (it is nullif'd at staging). A non-zero on any of the four RAW columns confirms the discrepancy.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where establishment_name = '') as name_empty,
  count(*) filter (where establishment_name <> '' and establishment_name ~ '^\s+$') as name_ws,
  count(*) filter (where city = '') as city_empty,
  count(*) filter (where city <> '' and city ~ '^\s+$') as city_ws,
  count(*) filter (where state = '') as state_empty,
  count(*) filter (where state <> '' and state ~ '^\s+$') as state_ws,
  count(*) filter (where zip = '') as zip_empty,
  count(*) filter (where zip <> '' and zip ~ '^\s+$') as zip_ws,
  count(*) filter (where address = '') as address_empty
from silver.firm_usda_attributes;

-- ----------------------------------------------------------------------------------
-- firm_usda_status_meaningful_emptystring   [empty_string]   target: silver.firm_usda_attributes
-- purpose : Confirm status_regulated_est carries '' as a MEANINGFUL value (not a leak) and carries no whitespace-only anomaly — so the blank-freetext guard correctly excludes it.
-- CONFORMS: status_empty_meaningful > 0 (the documented ~90% active rows — EXPECTED, do not normalize). status_ws_anomaly = 0 (whitespace-only would be an anomaly).
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where status_regulated_est = '') as status_empty_meaningful,
  count(*) filter (where status_regulated_est <> '' and status_regulated_est ~ '^\s+$') as status_ws_anomaly
from silver.firm_usda_attributes;

-- ----------------------------------------------------------------------------------
-- firm_usda_status_enum_domain   [enum_domain]   target: silver.firm_usda_attributes
-- purpose : Verify status_regulated_est distinct value set matches the documented closed domain {'',Inactive} (code does not CASE-constrain it; only the dbt accepted_values test does).
-- CONFORMS: Exactly two non-null values: '' and 'Inactive' (plus possibly <NULL> if any null slipped in). Any third distinct value is an undocumented enum drift the accepted_values test would catch.
-- ----------------------------------------------------------------------------------
select coalesce(status_regulated_est, '<NULL>') as status_value, count(*) as n
from silver.firm_usda_attributes
group by status_regulated_est
order by n desc;

-- ----------------------------------------------------------------------------------
-- firm_uscg_sidecar_emptystring   [empty_string]   target: silver.firm_uscg_attributes
-- purpose : Confirm the CASE-normalized USCG detail text columns carry no '' (they should be clean) and probe the two RAW lineage passthroughs (uscg_directory_id, detail_url) for residual ''.
-- CONFORMS: company_empty/dba_empty/address_empty/state_empty/status_empty = 0 (CASE-normalized at staging). dir_id_empty/detail_url_empty are the open question — 0 expected if bronze never emitted '' for these hash-excluded lineage ids; a non-zero confirms the undocumented raw-passthrough asymmetry.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where company_name = '') as company_empty,
  count(*) filter (where dba = '') as dba_empty,
  count(*) filter (where address = '') as address_empty,
  count(*) filter (where state = '') as state_empty,
  count(*) filter (where status = '') as status_empty,
  count(*) filter (where uscg_directory_id = '') as dir_id_empty,
  count(*) filter (where detail_url = '') as detail_url_empty
from silver.firm_uscg_attributes;

-- ----------------------------------------------------------------------------------
-- firm_dim_grain_uniqueness   [grain]   target: silver.firm
-- purpose : Verify firm primary grain: one row per canonical firm_id (matches the unique index + not_null/unique dbt tests).
-- CONFORMS: total_rows = distinct_firm_id (unique grain) and null_firm_id = 0 (not_null).
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(distinct firm_id) as distinct_firm_id,
  count(*) filter (where firm_id is null) as null_firm_id
from silver.firm;

-- ----------------------------------------------------------------------------------
-- firm_observed_company_ids_null_shape   [nullability]   target: silver.firm
-- purpose : Settle the doc_gap: confirm observed_company_ids is SQL NULL (not '[]') for id-less firms, and never contains a JSON null element. Informs whether the contract should coalesce to '[]'.
-- CONFORMS: null_ids > 0 (NHTSA-only / id-less firms yield SQL NULL, per the FILTER clause), empty_array_ids = 0 (the FILTER means an all-null group is NULL not '[]'), contains_json_null = 0 (FILTER strips nulls). Confirms the undocumented NULL-vs-array shape.
-- ----------------------------------------------------------------------------------
select
  count(*) as total_firms,
  count(*) filter (where observed_company_ids is null) as null_ids,
  count(*) filter (where observed_company_ids = '[]'::jsonb) as empty_array_ids,
  count(*) filter (where observed_company_ids @> 'null'::jsonb) as contains_json_null
from silver.firm;

-- ----------------------------------------------------------------------------------
-- firm_observed_names_never_empty   [nullability]   target: silver.firm
-- purpose : Verify observed_names is always a non-null, non-empty jsonb array (>=1 element by construction) — the documented-but-untested invariant.
-- CONFORMS: null_names = 0 and empty_array_names = 0 (every firm group has >=1 non-null/non-empty raw_name).
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where observed_names is null) as null_names,
  count(*) filter (where jsonb_array_length(observed_names) = 0) as empty_array_names
from silver.firm;

-- ----------------------------------------------------------------------------------
-- firm_fda_attributes_grain_and_fei   [grain]   target: silver.firm_fda_attributes
-- purpose : Verify one row per firm_fei_num (not_null + unique hard key) and that the current view (dbt_valid_to is null) collapsed cleanly.
-- CONFORMS: total_rows = distinct_fei (unique) and null_fei = 0 (excluded by where firm_fei_num is not null in the snapshot driver).
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(distinct firm_fei_num) as distinct_fei,
  count(*) filter (where firm_fei_num is null) as null_fei
from silver.firm_fda_attributes;

-- ----------------------------------------------------------------------------------
-- firm_fda_fei_functional_index_present   [other]   target: silver.firm_fda_attributes
-- purpose : Confirm the load-bearing functional (firm_fei_num::text) index exists post-build (the drop-then-create oscillation footgun) and the declared btree on firm_state_cd / unique on firm_fei_num are present.
-- CONFORMS: Includes idx_firm_fda_attributes_fei_text on ((firm_fei_num::text)), a unique index on firm_fei_num, and a btree on firm_state_cd. The functional FEI::text index MUST be present (its absence = the oscillation bug recurred).
-- ----------------------------------------------------------------------------------
select indexname, indexdef
from pg_indexes
where schemaname = 'silver' and tablename = 'firm_fda_attributes'
order by indexname;

-- ----------------------------------------------------------------------------------
-- firm_usda_sidecar_grain   [grain]   target: silver.firm_usda_attributes
-- purpose : Verify one row per establishment_id (not_null + unique current-view grain).
-- CONFORMS: total_rows = distinct_estab and null_estab = 0.
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(distinct establishment_id) as distinct_estab,
  count(*) filter (where establishment_id is null) as null_estab
from silver.firm_usda_attributes;

-- ----------------------------------------------------------------------------------
-- firm_uscg_sidecar_grain_and_bool_nonnull   [grain]   target: silver.firm_uscg_attributes
-- purpose : Verify one current row per MIC (not_null + unique) and that derived booleans / prior_holders are never NULL.
-- CONFORMS: total_rows = distinct_mic, null_mic = 0; all three boolean null_* = 0 (boolean predicates over coalesce never NULL); null_prior_holders = 0 (to_jsonb of an array, possibly '[]').
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(distinct mic) as distinct_mic,
  count(*) filter (where mic is null) as null_mic,
  count(*) filter (where mic_has_prior_holder is null) as null_has_prior,
  count(*) filter (where mic_oob_recycled is null) as null_oob,
  count(*) filter (where mic_renamed_not_recycled is null) as null_renamed,
  count(*) filter (where prior_holders is null) as null_prior_holders
from silver.firm_uscg_attributes;

-- ----------------------------------------------------------------------------------
-- firm_uscg_oob_subset_invariant   [other]   target: silver.firm_uscg_attributes
-- purpose : Verify the documented invariant mic_oob_recycled is a SUBSET of mic_has_prior_holder, and mic_renamed_not_recycled is disjoint from mic_oob_recycled.
-- CONFORMS: Both = 0 (oob implies prior holder; a pure rename cannot also be OOB-recycled).
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where mic_oob_recycled and not mic_has_prior_holder) as oob_not_prior_violation,
  count(*) filter (where mic_renamed_not_recycled and mic_oob_recycled) as renamed_and_oob_violation
from silver.firm_uscg_attributes;

-- ----------------------------------------------------------------------------------
-- uscg_mic_reassignment_year_sanity   [range_sanity]   target: silver.uscg_mic_reassignment_years
-- purpose : Verify current_holder_since_year is a sane 4-digit year (19xx/20xx, not in the future), not_null, and grain is one row per MIC.
-- CONFORMS: total_rows = distinct_mic (one row per MIC), null_year = 0 (HAVING max(oob_year) is not null), min_year >= 1900 (regex matches 19xx/20xx), max_year <= current year, out_of_range = 0.
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(distinct mic) as distinct_mic,
  count(*) filter (where current_holder_since_year is null) as null_year,
  min(current_holder_since_year) as min_year, max(current_holder_since_year) as max_year,
  count(*) filter (where current_holder_since_year < 1900 or current_holder_since_year > extract(year from now())) as out_of_range
from silver.uscg_mic_reassignment_years;

-- ----------------------------------------------------------------------------------
-- firm_fei_edges_grain_and_nonnull   [grain]   target: silver.firm_fei_edges
-- purpose : Verify firm_fei_edges is one row per distinct edge (NOT unique on firm_id — a name maps to multiple FEIs) and that firm_id/firm_fei_num/current_fei are non-null/non-empty.
-- CONFORMS: total_rows >= distinct_firm_id (firm_id intentionally NOT unique here — pre-clustering edges). bad_firm_id / bad_fei / bad_current_fei / bad_current_name all = 0 (WHERE clauses guarantee non-null/non-empty; coalesce keys never empty).
-- ----------------------------------------------------------------------------------
select
  count(*) as total_rows,
  count(distinct firm_id) as distinct_firm_id,
  count(*) filter (where firm_id is null or firm_id = '') as bad_firm_id,
  count(*) filter (where firm_fei_num is null or firm_fei_num = '') as bad_fei,
  count(*) filter (where current_fei is null or current_fei = '') as bad_current_fei,
  count(*) filter (where current_name is null or current_name = '') as bad_current_name
from silver.firm_fei_edges;

-- ----------------------------------------------------------------------------------
-- firm_fda_address_emptystring_clean   [empty_string]   target: silver.firm_fda_attributes
-- purpose : Confirm the FDA sidecar address/name columns carry no '' (nullif'd at staging / nullif(trim) in the snapshot driver) — regression guard, not expected to fail.
-- CONFORMS: All = 0 (FDA sidecar columns are nullif'd at stg_fda_recalls.sql lines 52-59 and firm_legal_nam additionally nullif(trim) in the snapshot driver). Any non-zero = a regression.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where firm_legal_nam = '') as legal_empty,
  count(*) filter (where firm_city_nam = '') as city_empty,
  count(*) filter (where firm_line1_adr = '') as adr_empty,
  count(*) filter (where firm_state_cd = '') as state_empty,
  count(*) filter (where firm_country_nam = '') as country_empty
from silver.firm_fda_attributes;
