-- Silver/Gold Provenance Audit — SCD-2 snapshots (silver_snapshots)
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- SCHEMAS: ALL staging views / silver tables / gold marts+facts / dbt seeds live in schema "public"
--   (dbt generate_schema_name -> target.schema = public; only the SCD-2 snapshots set a custom schema).
--   SCD-2 snapshots live in "silver_snapshots". seeds: public.us_state_abbr, public.country_iso.
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit_2026_w25.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- snapshot_column_types   [type]   target: silver_snapshots.firm_fda_attributes_snapshot, firm_usda_attributes_snapshot, firm_uscg_attributes_snapshot, nhtsa_recall_product_snapshot
-- purpose : Confirm the produced Postgres types of every snapshot column — especially the disputed ones: nhtsa model_year (claimed integer, expected text), bgman/endman (claimed text, expected timestamptz), uscg out_of_business/in_business/date_modified (claimed text, expected timestamptz/date), usda geolocation (claimed jsonb, expected text), potaff (text).
-- CONFORMS: nhtsa_recall_product_snapshot.model_year = text (NOT integer); bgman/endman = timestamp with time zone; firm_uscg_attributes_snapshot.out_of_business/in_business/date_modified = timestamp with time zone (or date); firm_usda_attributes_snapshot.geolocation/county = text (NOT jsonb); activities/dbas = jsonb; potaff = text; all dbt_valid_from/to/dbt_updated_at = timestamp; dbt_scd_id = text.
-- ----------------------------------------------------------------------------------
select table_name, column_name, data_type, is_nullable from information_schema.columns where table_schema = 'silver_snapshots' and table_name in ('firm_fda_attributes_snapshot','firm_usda_attributes_snapshot','firm_uscg_attributes_snapshot','nhtsa_recall_product_snapshot') order by table_name, ordinal_position;

-- ----------------------------------------------------------------------------------
-- nhtsa_snapshot_grain_unique   [grain]   target: silver_snapshots.nhtsa_recall_product_snapshot
-- purpose : Verify SCD-2 grain: one version row per (recall_product_id, dbt_valid_from); matches the dbt unique_combination_of_columns test.
-- CONFORMS: dup_versions = 0; current_rows = distinct_current_anchors (the current view dbt_valid_to is null is one row per 7-tuple anchor).
-- ----------------------------------------------------------------------------------
select count(*) as total_rows, count(*) - count(distinct (recall_product_id, dbt_valid_from)) as dup_versions, count(*) filter (where dbt_valid_to is null) as current_rows, count(distinct recall_product_id) filter (where dbt_valid_to is null) as distinct_current_anchors from silver_snapshots.nhtsa_recall_product_snapshot;

-- ----------------------------------------------------------------------------------
-- firm_snapshots_grain_unique   [grain]   target: silver_snapshots.firm_fda_attributes_snapshot, firm_usda_attributes_snapshot, firm_uscg_attributes_snapshot
-- purpose : Verify each firm snapshot is one version per (anchor, dbt_valid_from) and the current view is one row per anchor.
-- CONFORMS: dup_versions = 0 and current_anchor_excess = 0 for all three (one version per anchor per valid_from; current view one row per anchor).
-- ----------------------------------------------------------------------------------
select 'fda' src, count(*) - count(distinct (firm_fei_num, dbt_valid_from)) as dup_versions, count(*) filter (where dbt_valid_to is null) - count(distinct firm_fei_num) filter (where dbt_valid_to is null) as current_anchor_excess from silver_snapshots.firm_fda_attributes_snapshot union all select 'usda', count(*) - count(distinct (establishment_number, dbt_valid_from)), count(*) filter (where dbt_valid_to is null) - count(distinct establishment_number) filter (where dbt_valid_to is null) from silver_snapshots.firm_usda_attributes_snapshot union all select 'uscg', count(*) - count(distinct (mic, dbt_valid_from)), count(*) filter (where dbt_valid_to is null) - count(distinct mic) filter (where dbt_valid_to is null) from silver_snapshots.firm_uscg_attributes_snapshot;

-- ----------------------------------------------------------------------------------
-- snapshot_anchor_not_null   [nullability]   target: all four silver_snapshots
-- purpose : Confirm the anchor (unique_key) and dbt_scd_id are never NULL — the only not_null contract the _snapshots.yml declares.
-- CONFORMS: n_null_anchor = 0 and n_null_scd = 0 for all four snapshots.
-- ----------------------------------------------------------------------------------
select 'fda firm_fei_num' k, count(*) filter (where firm_fei_num is null) n_null_anchor, count(*) filter (where dbt_scd_id is null) n_null_scd from silver_snapshots.firm_fda_attributes_snapshot union all select 'usda establishment_number', count(*) filter (where establishment_number is null), count(*) filter (where dbt_scd_id is null) from silver_snapshots.firm_usda_attributes_snapshot union all select 'uscg mic', count(*) filter (where mic is null), count(*) filter (where dbt_scd_id is null) from silver_snapshots.firm_uscg_attributes_snapshot union all select 'nhtsa recall_product_id', count(*) filter (where recall_product_id is null), count(*) filter (where dbt_scd_id is null) from silver_snapshots.nhtsa_recall_product_snapshot;

-- ----------------------------------------------------------------------------------
-- usda_snapshot_empty_string_text   [empty_string]   target: silver_snapshots.firm_usda_attributes_snapshot
-- purpose : Detect '' / whitespace-only in the USDA text columns that staging does NOT nullif (establishment_name, city, state, zip, county, geolocation) — these reach the published mart_firm_profile.firm_usda_attributes. status_regulated_est is reported separately because '' is meaningful there (do not treat as a leak).
-- CONFORMS: For a CONFORMING snapshot all n_empty = 0 and n_ws = 0. A nonzero count on establishment_name/city/state/zip/county/geolocation confirms the staging ''→NULL gap (these are NOT the already-fixed columns). status_regulated_est '' is excluded here because '' is its documented active value.
-- ----------------------------------------------------------------------------------
select 'establishment_name' col, count(*) filter (where establishment_name = '') n_empty, count(*) filter (where establishment_name <> '' and establishment_name ~ '^\s+$') n_ws from silver_snapshots.firm_usda_attributes_snapshot union all select 'city', count(*) filter (where city = ''), count(*) filter (where city <> '' and city ~ '^\s+$') from silver_snapshots.firm_usda_attributes_snapshot union all select 'state', count(*) filter (where state = ''), count(*) filter (where state <> '' and state ~ '^\s+$') from silver_snapshots.firm_usda_attributes_snapshot union all select 'zip', count(*) filter (where zip = ''), count(*) filter (where zip <> '' and zip ~ '^\s+$') from silver_snapshots.firm_usda_attributes_snapshot union all select 'county', count(*) filter (where county = ''), count(*) filter (where county <> '' and county ~ '^\s+$') from silver_snapshots.firm_usda_attributes_snapshot union all select 'geolocation', count(*) filter (where geolocation = ''), count(*) filter (where geolocation <> '' and geolocation ~ '^\s+$') from silver_snapshots.firm_usda_attributes_snapshot;

-- ----------------------------------------------------------------------------------
-- usda_status_regulated_est_enum   [enum_domain]   target: silver_snapshots.firm_usda_attributes_snapshot
-- purpose : Confirm status_regulated_est domain is exactly {'', 'Inactive'} (the documented accepted_values where '' = active, by design) — verifies '' is meaningful, not a leak.
-- CONFORMS: Only '' (majority, ~90%) and 'Inactive' (~10%); no '<NULL>' and no third value. '' is expected and correct here (do NOT normalize).
-- ----------------------------------------------------------------------------------
select coalesce(status_regulated_est, '<NULL>') as status_value, count(*) as n from silver_snapshots.firm_usda_attributes_snapshot group by status_regulated_est order by n desc;

-- ----------------------------------------------------------------------------------
-- fda_snapshot_empty_string_text   [empty_string]   target: silver_snapshots.firm_fda_attributes_snapshot
-- purpose : Confirm the FDA check_cols are ''-free — stg_fda_recalls already nullifs firm_legal_nam/firm_city_nam/firm_country_nam/firm_state_cd/firm_state_prvnc_nam/firm_postal_cd/firm_line1_adr/firm_line2_adr/firm_surviving_nam (ADR 0027). This verifies the upstream nullif holds across the corpus. firm_surviving_fei is an id (reported for data-quality, not as a normalization gap).
-- CONFORMS: All n_empty = 0 (upstream stg_fda_recalls nullif holds). A nonzero firm_surviving_fei would be an id-integrity issue, not a normalization gap; a nonzero on the nullif'd columns would mean staging nullif was bypassed.
-- ----------------------------------------------------------------------------------
select 'firm_legal_nam' col, count(*) filter (where firm_legal_nam = '') n_empty from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_city_nam', count(*) filter (where firm_city_nam = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_country_nam', count(*) filter (where firm_country_nam = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_state_cd', count(*) filter (where firm_state_cd = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_state_prvnc_nam', count(*) filter (where firm_state_prvnc_nam = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_postal_cd', count(*) filter (where firm_postal_cd = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_line1_adr', count(*) filter (where firm_line1_adr = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_line2_adr', count(*) filter (where firm_line2_adr = '') from silver_snapshots.firm_fda_attributes_snapshot union all select 'firm_surviving_nam', count(*) filter (where firm_surviving_nam = '') from silver_snapshots.firm_fda_attributes_snapshot;  -- firm_surviving_fei removed: it is BIGINT, cannot hold '' (audited 2026-W25)

-- ----------------------------------------------------------------------------------
-- uscg_snapshot_empty_string_text   [empty_string]   target: silver_snapshots.firm_uscg_attributes_snapshot
-- purpose : Confirm the USCG text check_cols are ''-free — stg_uscg_manufacturer_details CASE-maps '-'/'UNK'/'' → NULL (and nullif(state,'')) before the snapshot. Verifies the upstream CASE holds across the corpus.
-- CONFORMS: All n_empty = 0 (upstream stg_uscg_manufacturer_details CASE-to-NULL + nullif(state,'') hold). company_name additionally never NULL (snapshot WHERE company_name is not null).
-- ----------------------------------------------------------------------------------
select 'company_name' col, count(*) filter (where company_name = '') n_empty from silver_snapshots.firm_uscg_attributes_snapshot union all select 'dba', count(*) filter (where dba = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'parent_company', count(*) filter (where parent_company = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'parent_mic', count(*) filter (where parent_mic = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'past_company_1', count(*) filter (where past_company_1 = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'past_company_2', count(*) filter (where past_company_2 = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'past_company_3', count(*) filter (where past_company_3 = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'address', count(*) filter (where address = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'city', count(*) filter (where city = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'state', count(*) filter (where state = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'zip', count(*) filter (where zip = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'country', count(*) filter (where country = '') from silver_snapshots.firm_uscg_attributes_snapshot union all select 'status', count(*) filter (where status = '') from silver_snapshots.firm_uscg_attributes_snapshot;

-- ----------------------------------------------------------------------------------
-- nhtsa_snapshot_empty_string_text   [empty_string]   target: silver_snapshots.nhtsa_recall_product_snapshot
-- purpose : Probe '' on the NHTSA TEXT columns ONLY (exclude bgman/endman — they are timestamptz, not text). Carried anchor components (maketxt/modeltxt/yeartxt/compname/rcl_cmpt_id/mfr_comp_ptno) legitimately contain '' per ADR 0030 allow_null_identity, so '' there is informational, not a defect. fmvss/rcltype/potaff/mfgname/mfgtxt/mfr_comp_desc/mfr_comp_name are the demoted check_cols — '' there is source-verbatim (NHTSA flat-file absent-value sentinel) and downstream normalization happens in recall_product.sql's serving normalize CTE (already fixed there).
-- CONFORMS: Informational, not pass/fail at this layer. Anchor components and check_cols MAY carry '' (NHTSA absent-value sentinel; ADR 0030). The serving fix is downstream in recall_product.sql. Use this to size how many '' values exist and confirm they are confined to the snapshot/identity layer (not the already-fixed served recall_product free-text).
-- ----------------------------------------------------------------------------------
select 'maketxt(anchor)' col, count(*) filter (where maketxt = '') n_empty from silver_snapshots.nhtsa_recall_product_snapshot union all select 'modeltxt(anchor)', count(*) filter (where modeltxt = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'compname(anchor)', count(*) filter (where compname = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'rcl_cmpt_id(anchor)', count(*) filter (where rcl_cmpt_id = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'mfr_comp_ptno(anchor)', count(*) filter (where mfr_comp_ptno = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'mfr_comp_desc(check)', count(*) filter (where mfr_comp_desc = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'mfr_comp_name(check)', count(*) filter (where mfr_comp_name = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'fmvss(check)', count(*) filter (where fmvss = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'rcltype(check)', count(*) filter (where rcltype = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'potaff(check)', count(*) filter (where potaff = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'mfgname(check)', count(*) filter (where mfgname = '') from silver_snapshots.nhtsa_recall_product_snapshot union all select 'mfgtxt(check)', count(*) filter (where mfgtxt = '') from silver_snapshots.nhtsa_recall_product_snapshot;

-- ----------------------------------------------------------------------------------
-- nhtsa_model_year_text_sanity   [range_sanity]   target: silver_snapshots.nhtsa_recall_product_snapshot
-- purpose : Given model_year is produced as TEXT (not the ADR 0009 SMALLINT), confirm the 9999 sentinel is mapped to NULL and that every non-null value is a 4-digit year string (so a downstream ::int cast would not fail).
-- CONFORMS: n_sentinel_unmapped = 0 (9999 mapped to NULL in staging); n_nonnumeric = 0 (every non-null model_year is a 4-digit string); min_yr/max_yr within a sane vehicle-year range (e.g. roughly 1900..current+2). Confirms the text representation is cast-safe even though the contract type is unmet.
-- ----------------------------------------------------------------------------------
select count(*) total, count(*) filter (where model_year is null) n_null, count(*) filter (where model_year = '9999') n_sentinel_unmapped, count(*) filter (where model_year is not null and model_year !~ '^[0-9]{4}$') n_nonnumeric, min(model_year) min_yr, max(model_year) max_yr from silver_snapshots.nhtsa_recall_product_snapshot;

-- ----------------------------------------------------------------------------------
-- nhtsa_potaff_int_cast_safe   [range_sanity]   target: silver_snapshots.nhtsa_recall_product_snapshot
-- purpose : potaff is carried as TEXT; verify every non-null/non-empty value is an integer string so the downstream cast(potaff as int) in the recall_product/fct_units_recalled path cannot error.
-- CONFORMS: n_noninteger = 0 (every populated potaff is digits). If n_empty > 0, the downstream cast must nullif('') first — flag for review.
-- ----------------------------------------------------------------------------------
select count(*) filter (where potaff is null) n_null, count(*) filter (where potaff = '') n_empty, count(*) filter (where potaff is not null and potaff <> '' and potaff !~ '^[0-9]+$') n_noninteger from silver_snapshots.nhtsa_recall_product_snapshot;

-- ----------------------------------------------------------------------------------
-- uscg_status_enum_cardinality   [enum_domain]   target: silver_snapshots.firm_uscg_attributes_snapshot
-- purpose : Capture the live domain of the open-enum status check_col (no accepted_values test exists) to confirm it matches the bronze-observed {In Business, Inactive, Federal or State Agency} and surface any drift.
-- CONFORMS: Values confined to {'In Business','Inactive','Federal or State Agency','<NULL>'}; any other value is undocumented drift worth an accepted_values(warn) test.
-- ----------------------------------------------------------------------------------
select coalesce(status, '<NULL>') as status_value, count(*) as n from silver_snapshots.firm_uscg_attributes_snapshot group by status order by n desc;

-- ----------------------------------------------------------------------------------
-- nhtsa_recltype_enum_cardinality   [enum_domain]   target: silver_snapshots.nhtsa_recall_product_snapshot
-- purpose : rcltype is a check_col; stg_nhtsa_recalls.yml documents accepted_values {V,T,E,C,I,X} (warn). Confirm the snapshot's rcltype stays within that domain.
-- CONFORMS: Values within {V,T,E,C,I,X} (I/X rare <0.2%); '<NULL>' tolerated; any other value is drift.
-- ----------------------------------------------------------------------------------
select coalesce(rcltype, '<NULL>') as rcltype_value, count(*) as n from silver_snapshots.nhtsa_recall_product_snapshot group by rcltype order by n desc;

-- ----------------------------------------------------------------------------------
-- uscg_parent_mic_join_alignment   [normalization]   target: silver_snapshots.firm_uscg_attributes_snapshot
-- purpose : parent_mic is carried raw (not upper(trim)-normalized like the anchor mic). Detect any non-null parent_mic whose normalized form does not match a current anchor mic — a parent-chain join would miss those.
-- CONFORMS: Informational. n_unnormalized > 0 means parent_mic carries case/whitespace variants the anchor normalization would have folded; n_orphan_parent is parent MICs not present as anchors (may be legitimate if parent is out-of-directory). Use to decide whether parent_mic needs upper(trim) alignment.
-- ----------------------------------------------------------------------------------
with cur as (select mic from silver_snapshots.firm_uscg_attributes_snapshot where dbt_valid_to is null) select count(*) filter (where parent_mic is not null) as n_parent, count(*) filter (where parent_mic is not null and upper(trim(parent_mic)) <> parent_mic) as n_unnormalized, count(*) filter (where parent_mic is not null and upper(trim(parent_mic)) not in (select mic from cur)) as n_orphan_parent from silver_snapshots.firm_uscg_attributes_snapshot s where dbt_valid_to is null;

-- ----------------------------------------------------------------------------------
-- snapshot_valid_to_current_consistency   [nullability]   target: all four silver_snapshots
-- purpose : Confirm the current-view contract (dbt_valid_to IS NULL = current version) is well-formed: exactly the open intervals have NULL dbt_valid_to and dbt_valid_from is never NULL.
-- CONFORMS: n_null_from = 0 for all four (dbt manages dbt_valid_from NOT NULL); n_current > 0 and equals the distinct-anchor count from the grain checks (every anchor has exactly one open interval).
-- ----------------------------------------------------------------------------------
select 'fda' src, count(*) filter (where dbt_valid_from is null) n_null_from, count(*) filter (where dbt_valid_to is null) n_current from silver_snapshots.firm_fda_attributes_snapshot union all select 'usda', count(*) filter (where dbt_valid_from is null), count(*) filter (where dbt_valid_to is null) from silver_snapshots.firm_usda_attributes_snapshot union all select 'uscg', count(*) filter (where dbt_valid_from is null), count(*) filter (where dbt_valid_to is null) from silver_snapshots.firm_uscg_attributes_snapshot union all select 'nhtsa', count(*) filter (where dbt_valid_from is null), count(*) filter (where dbt_valid_to is null) from silver_snapshots.nhtsa_recall_product_snapshot;
