-- Silver/Gold Provenance Audit — Gold — serving marts (published read contract, ADR 0042)
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- Schemas: staging views = "staging"; silver tables = "silver"; gold = "gold"; dbt seeds = "public" (us_state_abbr, country_iso).
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- gold_marts_information_schema_type_sweep   [type]   target: gold.mart_recall_summary, gold.mart_product_search, gold.mart_firm_profile, gold.gold_meta
-- purpose : Schema-agnostic sweep of every served column's declared data type + is_nullable, so no column can silently drift type (e.g. distinct_products bigint vs int, array vs scalar, jsonb vs text). Compare output against the contract/doc type per column.
-- CONFORMS: One row per column. Spot-checks: mart_recall_summary.recall_event_id/source/title/url/recall_reason/classification text; announced_at/published_at/first_seen_at/last_seen_at timestamptz (udt timestamptz); is_active/is_currently_active/was_ever_retracted/has_been_edited boolean; distribution_state_codes/distribution_country_codes _text (text[]); firms/product_names/models/hins/hazards/product_upcs jsonb; search_vector tsvector. mart_product_search.upc text. mart_firm_profile.firm_usda_attributes/uscg/fda jsonb, roles/recalls_by_source/observed_company_ids/observed_names/alternate_names jsonb, distinct_products bigint/numeric. gold_meta.rebuilt_at timestamptz, schema_version text.
-- ----------------------------------------------------------------------------------
select table_name, column_name, ordinal_position, data_type, udt_name, is_nullable
from information_schema.columns
where table_schema = 'gold'
  and table_name in ('mart_recall_summary','mart_product_search','mart_firm_profile','gold_meta')
order by table_name, ordinal_position;

-- ----------------------------------------------------------------------------------
-- gold_marts_empty_string_and_whitespace_sweep   [empty_string]   target: gold.mart_recall_summary, gold.mart_product_search, gold.mart_firm_profile (all text columns)
-- purpose : Extend the trigger probe to THIS group: count '' and whitespace-only values per served text column. The known-risk columns are mart_recall_summary.url (CPSC/USCG), reason_category, distribution_states; mart_product_search.url/recall_title/firm_name (inherited), model_year, hin, source_recall_id; and the already-fixed product_name/product_description/model/type (expect 0 to confirm the fix held).
-- CONFORMS: ALL rows n_empty=0 AND n_whitespace=0 for a conforming DB. A non-zero on mart_recall_summary.url / mart_product_search.url confirms the CPSC/USCG url leak; non-zero on title/recall_reason/product_name/product_description would mean the already-shipped fix regressed; non-zero on model_year/hin breaks the exact-lookup assumption.
-- ----------------------------------------------------------------------------------
select 'mart_recall_summary' as obj, 'url' as col,
       count(*) filter (where url = '') as n_empty,
       count(*) filter (where url <> '' and url ~ '^\s+$') as n_whitespace
from gold.mart_recall_summary
union all select 'mart_recall_summary','reason_category',
       count(*) filter (where reason_category = ''),
       count(*) filter (where reason_category <> '' and reason_category ~ '^\s+$')
from gold.mart_recall_summary
union all select 'mart_recall_summary','distribution_states',
       count(*) filter (where distribution_states = ''),
       count(*) filter (where distribution_states <> '' and distribution_states ~ '^\s+$')
from gold.mart_recall_summary
union all select 'mart_recall_summary','title',
       count(*) filter (where title = ''), count(*) filter (where title <> '' and title ~ '^\s+$')
from gold.mart_recall_summary
union all select 'mart_recall_summary','recall_reason',
       count(*) filter (where recall_reason = ''), count(*) filter (where recall_reason <> '' and recall_reason ~ '^\s+$')
from gold.mart_recall_summary
union all select 'mart_product_search','model_year',
       count(*) filter (where model_year = ''), count(*) filter (where model_year <> '' and model_year ~ '^\s+$')
from gold.mart_product_search
union all select 'mart_product_search','hin',
       count(*) filter (where hin = ''), count(*) filter (where hin <> '' and hin ~ '^\s+$')
from gold.mart_product_search
union all select 'mart_product_search','product_name',
       count(*) filter (where product_name = ''), count(*) filter (where product_name <> '' and product_name ~ '^\s+$')
from gold.mart_product_search
union all select 'mart_product_search','product_description',
       count(*) filter (where product_description = ''), count(*) filter (where product_description <> '' and product_description ~ '^\s+$')
from gold.mart_product_search
union all select 'mart_product_search','url',
       count(*) filter (where url = ''), count(*) filter (where url <> '' and url ~ '^\s+$')
from gold.mart_product_search;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_source_enum   [enum_domain]   target: gold.mart_recall_summary.source
-- purpose : Confirm source is the closed UPPERCASE 5-value domain (ADR 0042 load-bearing for the API md5 key recipe).
-- CONFORMS: Exactly 5 rows with source in {CPSC,FDA,USDA,NHTSA,USCG}, all UPPERCASE, no NULL, no 'ALL', no other value.
-- ----------------------------------------------------------------------------------
select source, count(*) as n
from gold.mart_recall_summary
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_distribution_scope_enum_and_notnull   [enum_domain]   target: gold.mart_recall_summary.distribution_scope
-- purpose : Confirm distribution_scope is the closed 4-value enum with zero NULLs (the macro-produced domain that the _gold.yml accepted_values+not_null tests guard).
-- CONFORMS: Exactly the 4 rows {Nationwide,Regional,Unspecified,International}; no '<NULL>' row; no 5th value. (Approx volumes per 2026-06-14 audit: Nationwide ~42k, Regional ~32k, Unspecified ~12k, International ~7k.)
-- ----------------------------------------------------------------------------------
select coalesce(distribution_scope,'<NULL>') as distribution_scope, count(*) as n
from gold.mart_recall_summary
group by distribution_scope
order by distribution_scope;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_classification_source_native_domain   [enum_domain]   target: gold.mart_recall_summary.classification (by source)
-- purpose : Confirm classification is SOURCE-NATIVE, not unified: FDA/USDA in Class I/II/III (+ possible NC/PHA), USCG in {H,L,M,S}, CPSC/NHTSA NULL. Detects any cross-source 'tidying' that would violate ADR 0042.
-- CONFORMS: CPSC rows only classification='<NULL>'; NHTSA rows only '<NULL>'; FDA/USDA classification in {Class I,Class II,Class III} (USDA may add Public Health Alert); USCG classification in {H,L,M,S}. No empty string ''. No source carrying another source's encoding.
-- ----------------------------------------------------------------------------------
select source, coalesce(classification,'<NULL>') as classification, count(*) as n
from gold.mart_recall_summary
group by source, classification
order by source, classification;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_is_active_tristate   [nullability]   target: gold.mart_recall_summary.is_active (by source)
-- purpose : Confirm is_active is tri-state and NULL exactly for CPSC and NHTSA (ADR 0042: must not collapse the NULL).
-- CONFORMS: CPSC: n_true=0,n_false=0,n_null=all. NHTSA: n_true=0,n_false=0,n_null=all. FDA/USDA/USCG: n_null may be 0 (or small) and n_true/n_false populated. No source where the tri-state collapsed.
-- ----------------------------------------------------------------------------------
select source,
       count(*) filter (where is_active is true)  as n_true,
       count(*) filter (where is_active is false) as n_false,
       count(*) filter (where is_active is null)  as n_null
from gold.mart_recall_summary
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_risk_level_usda_only   [nullability]   target: gold.mart_recall_summary.risk_level (by source)
-- purpose : Confirm risk_level is USDA-only (NULL for every non-USDA source) per ADR 0042.
-- CONFORMS: Only source='USDA' has n_risk_level_set > 0; CPSC/FDA/NHTSA/USCG all 0.
-- ----------------------------------------------------------------------------------
select source, count(*) filter (where risk_level is not null) as n_risk_level_set
from gold.mart_recall_summary
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_grain_uniqueness   [grain]   target: gold.mart_recall_summary
-- purpose : Confirm one row per recall_event (recall_event_id is the unique key the keyset cursor + detail lookup rely on).
-- CONFORMS: n_rows = n_distinct_event (grain is unique on recall_event_id) and n_null_key = 0.
-- ----------------------------------------------------------------------------------
select count(*) as n_rows,
       count(distinct recall_event_id) as n_distinct_event,
       count(*) filter (where recall_event_id is null) as n_null_key
from gold.mart_recall_summary;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_array_cols_nonnull_O1   [nullability]   target: gold.mart_recall_summary.product_names/models/hins/firms
-- purpose : Confirm the ADR 0042 O1 always-non-null jsonb arrays are never NULL (API models them as list[...], never None).
-- CONFORMS: All four counts = 0 (each coalesced to '[]'::jsonb). Any non-zero is an ADR 0042 contract violation.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where product_names is null) as null_product_names,
  count(*) filter (where models is null)        as null_models,
  count(*) filter (where hins is null)          as null_hins,
  count(*) filter (where firms is null)         as null_firms
from gold.mart_recall_summary;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_distribution_codes_null_vs_emptyarray   [nullability]   target: gold.mart_recall_summary.distribution_state_codes / distribution_country_codes
-- purpose : Empirically settle the LEFT-JOIN nullability discrepancy: distinguish NULL (no recall_distribution_area row) from '{}' (row exists, no states/countries). Confirms whether the mart leaves these arrays NULLABLE (unlike the O1 arrays).
-- CONFORMS: state_codes_null and country_codes_null are LARGE (all CPSC/NHTSA/USCG + FDA/USDA events with no recall_distribution_area row) — confirming the column is NULLABLE at mart grain, distinct from the silver '{}' coalesce. If these are 0 the mart is coalescing somewhere not visible; either way the result determines whether the doc/coalesce fix is needed.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where distribution_state_codes is null)   as state_codes_null,
  count(*) filter (where distribution_state_codes = '{}')     as state_codes_empty,
  count(*) filter (where distribution_country_codes is null)  as country_codes_null,
  count(*) filter (where distribution_country_codes = '{}')   as country_codes_empty
from gold.mart_recall_summary;

-- ----------------------------------------------------------------------------------
-- mart_product_search_grain_and_fk   [grain]   target: gold.mart_product_search
-- purpose : Confirm one row per recall_product (recall_product_id unique = API keyset cursor anchor) and recall_event_id FK is always populated (inner join guarantees it).
-- CONFORMS: n_rows = n_distinct_product (unique grain), n_null_pid = 0, n_null_eid = 0.
-- ----------------------------------------------------------------------------------
select count(*) as n_rows,
       count(distinct recall_product_id) as n_distinct_product,
       count(*) filter (where recall_product_id is null) as n_null_pid,
       count(*) filter (where recall_event_id is null)   as n_null_eid
from gold.mart_product_search;

-- ----------------------------------------------------------------------------------
-- mart_product_search_upc_all_null   [nullability]   target: gold.mart_product_search.upc
-- purpose : Confirm product-grain upc is 100% NULL (ADR 0024: API must not advertise product-grain UPC search; btree dropped G5). A non-null is a contract regression.
-- CONFORMS: n_upc_nonnull = 0 (every upc is NULL). Any non-zero is an ADR 0024 contract regression to escalate.
-- ----------------------------------------------------------------------------------
select count(*) as n_rows,
       count(upc) as n_upc_nonnull
from gold.mart_product_search;

-- ----------------------------------------------------------------------------------
-- mart_product_search_source_enum   [enum_domain]   target: gold.mart_product_search.source
-- purpose : Confirm source is the closed UPPERCASE 5-value domain at product grain (no 'ALL').
-- CONFORMS: Exactly {CPSC,FDA,USDA,NHTSA,USCG}, UPPERCASE, no NULL, no 'ALL'.
-- ----------------------------------------------------------------------------------
select source, count(*) as n
from gold.mart_product_search
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- mart_firm_profile_grain   [grain]   target: gold.mart_firm_profile
-- purpose : Confirm one row per canonical firm (firm_id unique, not null) — the /firms/{id} lookup key.
-- CONFORMS: n_rows = n_distinct_firm, n_null_firm = 0, n_null_canon = 0 (canonical_name not_null per _gold.yml).
-- ----------------------------------------------------------------------------------
select count(*) as n_rows,
       count(distinct firm_id) as n_distinct_firm,
       count(*) filter (where firm_id is null) as n_null_firm,
       count(*) filter (where canonical_name is null) as n_null_canon
from gold.mart_firm_profile;

-- ----------------------------------------------------------------------------------
-- mart_firm_profile_roles_domain   [enum_domain]   target: gold.mart_firm_profile.roles (unnested)
-- purpose : Confirm every element of the roles jsonb array is within the recall_event_firm.role enum {manufacturer,importer,distributor,establishment,filer} — detects any leaked 'retailer' (removed per ADR 0036) or other drift.
-- CONFORMS: Distinct role_value set is a subset of {manufacturer,importer,distributor,establishment,filer}. No 'retailer', no NULL, no empty string.
-- ----------------------------------------------------------------------------------
select elem as role_value, count(*) as n_firms
from gold.mart_firm_profile,
     lateral jsonb_array_elements_text(coalesce(roles,'[]'::jsonb)) as elem
group by elem
order by elem;

-- ----------------------------------------------------------------------------------
-- mart_firm_profile_sidecar_blocks_jsonb   [type]   target: gold.mart_firm_profile.firm_usda_attributes/firm_uscg_attributes/firm_fda_attributes
-- purpose : Confirm the three R5-renamed sidecar columns exist with jsonb type (ADR 0042 published contract names) and are populated for at least some firms (sanity that the lateral-unnest sidecar join is wired, not all-NULL).
-- CONFORMS: Each count > 0 (the sidecar join produces blocks for firms matching a USDA establishment_number / USCG MIC / FDA FEI respectively). All-zero on any would indicate the observed_company_ids unnest join silently broke.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where firm_usda_attributes is not null) as n_usda,
  count(*) filter (where firm_uscg_attributes is not null) as n_uscg,
  count(*) filter (where firm_fda_attributes is not null)  as n_fda
from gold.mart_firm_profile;

-- ----------------------------------------------------------------------------------
-- gold_meta_single_row_and_stamps   [grain]   target: gold.gold_meta
-- purpose : Confirm gold_meta is exactly one row with a non-null rebuilt_at (timestamptz) and non-null, non-empty schema_version (text) — the API ETag/version path depends on a single deterministic row.
-- CONFORMS: n_rows = 1, n_null_rebuilt = 0, n_bad_version = 0, schema_version_value = '1' (or the current manually-bumped value).
-- ----------------------------------------------------------------------------------
select count(*) as n_rows,
       count(*) filter (where rebuilt_at is null) as n_null_rebuilt,
       count(*) filter (where schema_version is null or schema_version = '') as n_bad_version,
       max(schema_version) as schema_version_value
from gold.gold_meta;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_published_at_notnull_and_sanity   [range_sanity]   target: gold.mart_recall_summary.published_at
-- purpose : Confirm published_at is the hard NOT-NULL serving sort/filter date (ADR contract: coalesced present for every row) and within a sane range (>=1940, not far future) — it anchors the keyset pagination index.
-- CONFORMS: n_null = 0 (not-null contract), n_too_old = 0, n_future = 0 (date-sanity floor 1940 + no future-dated publish).
-- ----------------------------------------------------------------------------------
select count(*) filter (where published_at is null) as n_null,
       count(*) filter (where published_at < timestamptz '1940-01-01') as n_too_old,
       count(*) filter (where published_at > now() + interval '2 days') as n_future
from gold.mart_recall_summary;

-- ----------------------------------------------------------------------------------
-- mart_recall_summary_announced_at_nullable_by_design   [nullability]   target: gold.mart_recall_summary.announced_at
-- purpose : Confirm announced_at is nullable by design (ADR contract) and the NULLs are bounded to the expected handful (e.g. ~20 FDA events per _silver.yml note), distinguishing intentional design-nulls from a widespread regression.
-- CONFORMS: announced_at NULLs are present (nullable by design) but bounded — concentrated in FDA (~20) with the rest near 0; a large/whole-source NULL block (e.g. all NHTSA) would be a regression to investigate.
-- ----------------------------------------------------------------------------------
select source, count(*) filter (where announced_at is null) as n_null_announced, count(*) as n_total
from gold.mart_recall_summary
group by source
order by source;
