-- Silver/Gold Provenance Audit — Gold — fct_* aggregates + dim_date
-- Generated by the data-provenance audit workflow (2026-06-19, branch chore/data-provenance). READ-ONLY.
-- Schemas: staging views = "staging"; silver tables = "silver"; gold = "gold"; dbt seeds = "public" (us_state_abbr, country_iso).
-- Empty-string EXCLUSIONS (do NOT run the '' probe on these): bgman/endman/in_business/out_of_business (timestamptz);
--   status_regulated_est ('' is a MEANINGFUL value); recall_event_history.old_value/new_value & recall_product_history NHTSA cols ('' by design).
-- For each block the CONFORMING result is stated; any deviation is a finding to triage against silver_gold_provenance_audit.md.
-- ============================================================================================

-- ----------------------------------------------------------------------------------
-- gold_facts_column_types   [type]   target: gold.dim_date, gold.fct_recalls_by_classification, gold.fct_recalls_by_country, gold.fct_recalls_by_firm, gold.fct_recalls_by_geography, gold.fct_recalls_by_month, gold.fct_recalls_by_week, gold.fct_recalls_by_year, gold.fct_recalls_monthly_trend, gold.fct_recall_status, gold.fct_units_recalled
-- purpose : Schema-agnostic sweep of every column's data_type / is_nullable across all gold-facts objects so no column can silently drift type (e.g. period stays date, event_count stays bigint, total_units stays numeric, source stays text).
-- CONFORMS: For each object the produced types from input C: period/date_day/month/period -> date; *_start columns date; year/quarter/month/iso_*/us_fiscal_year -> integer; event_count/recall_count/recalls_with_units/event_count_rank/active_recalls/product_count -> bigint; total_units/avg_units_per_recall/max_units/rolling_*_avg/yoy_pct_change -> numeric; source/classification/risk_level/status/geography_basis/state_code/country_code/unit_category/canonical_name -> text; first_recall_at/last_recall_at -> timestamp without time zone (follows recall_event.published_at). No unexpected column, no type drift.
-- ----------------------------------------------------------------------------------
select table_name, column_name, ordinal_position, data_type, is_nullable
from information_schema.columns
where table_schema = 'gold'
  and table_name in ('dim_date','fct_recalls_by_classification','fct_recalls_by_country','fct_recalls_by_firm','fct_recalls_by_geography','fct_recalls_by_month','fct_recalls_by_week','fct_recalls_by_year','fct_recalls_monthly_trend','fct_recall_status','fct_units_recalled')
order by table_name, ordinal_position;

-- ----------------------------------------------------------------------------------
-- classification_enum_domain   [enum_domain]   target: gold.fct_recalls_by_classification.classification
-- purpose : Confirm the REAL produced classification value set per source (the central enum finding): FDA emits 1/2/3/NC (NOT Class I/II/III), USDA emits 'Public Health Alert' (NOT 'PHA'), USCG H/L/M/S, CPSC/NHTSA NULL.
-- CONFORMS: FDA rows: classification in {'1','2','3','NC'}. USDA rows: classification in {'Class I','Class II','Class III','Public Health Alert'}. USCG rows: classification in {'H','L','M','S'}. CPSC/NHTSA rows: classification IS NULL. 'ALL' rollup rows carry the union of the above. NO value 'PHA' and NO FDA 'Class I/II/III' should appear (their presence would mean the input-C/doc enum was right and the code changed).
-- ----------------------------------------------------------------------------------
select source, classification, count(*) as n_rows, sum(event_count) as total_events
from gold.fct_recalls_by_classification
group by source, classification
order by source, classification nulls first;

-- ----------------------------------------------------------------------------------
-- risk_level_enum_domain_and_usda_only   [enum_domain]   target: gold.fct_recalls_by_classification.risk_level
-- purpose : Confirm risk_level's undocumented 4-value USDA-only domain and that it is NULL for every non-USDA source.
-- CONFORMS: Non-NULL risk_level only on source in ('USDA','ALL'); USDA risk_level in {'High - Class I','Low - Class II','Marginal - Class III','Public Health Alert'}. risk_level IS NULL for CPSC/FDA/NHTSA/USCG. Any non-NULL risk_level on a non-USDA source = a derivation bug.
-- ----------------------------------------------------------------------------------
select source, risk_level, count(*) as n_rows
from gold.fct_recalls_by_classification
group by source, risk_level
order by source, risk_level nulls first;

-- ----------------------------------------------------------------------------------
-- fct_source_enum_with_all   [enum_domain]   target: gold.fct_recalls_by_classification.source, gold.fct_recalls_by_month.source, gold.fct_recalls_by_week.source, gold.fct_recalls_by_year.source, gold.fct_recall_status.source, gold.fct_recalls_by_geography.source
-- purpose : Verify the closed UPPERCASE source enum + the 'ALL' GROUPING SETS rollup row are exactly {CPSC,FDA,USDA,NHTSA,USCG,ALL} for the rollup-bearing facts.
-- CONFORMS: Each object's source set is exactly {CPSC,FDA,USDA,NHTSA,USCG,ALL}; no lowercase, no other label, no NULL (coalesce(source,'ALL') guarantees non-null).
-- ----------------------------------------------------------------------------------
select 'fct_recalls_by_month' as obj, source, count(*) n from gold.fct_recalls_by_month group by source
union all select 'fct_recalls_by_week', source, count(*) from gold.fct_recalls_by_week group by source
union all select 'fct_recalls_by_year', source, count(*) from gold.fct_recalls_by_year group by source
union all select 'fct_recalls_by_classification', source, count(*) from gold.fct_recalls_by_classification group by source
union all select 'fct_recall_status', source, count(*) from gold.fct_recall_status group by source
union all select 'fct_recalls_by_geography', source, count(*) from gold.fct_recalls_by_geography group by source
order by obj, source;

-- ----------------------------------------------------------------------------------
-- monthly_trend_source_no_all   [enum_domain]   target: gold.fct_recalls_monthly_trend.source
-- purpose : Confirm fct_recalls_monthly_trend is the per-source-ONLY fact (no 'ALL' rollup), matching its doc and the no-coalesce code.
-- CONFORMS: source set is exactly {CPSC,FDA,USDA,NHTSA,USCG} with NO 'ALL' row. An 'ALL' row would be a bug (this model has a dense per-source spine, no rollup).
-- ----------------------------------------------------------------------------------
select source, count(*) as n_months
from gold.fct_recalls_monthly_trend
group by source
order by source;

-- ----------------------------------------------------------------------------------
-- units_recalled_source_and_category_enums   [enum_domain]   target: gold.fct_units_recalled.source, gold.fct_units_recalled.unit_category
-- purpose : Confirm fct_units_recalled excludes CPSC and 'ALL' (source in {NHTSA,USCG,FDA,USDA}) and unit_category stays the closed 4-value taxonomy with no NULL leak through the FDA/USDA passthrough.
-- CONFORMS: source in {NHTSA,USCG,FDA,USDA} only (no CPSC, no 'ALL'). NHTSA/USCG rows have unit_category='count'. FDA/USDA rows have unit_category in {count,weight,volume,grouping}. No NULL unit_category (filtered at source). No out-of-set category.
-- ----------------------------------------------------------------------------------
select source, unit_category, count(*) as n_rows
from gold.fct_units_recalled
group by source, unit_category
order by source, unit_category;

-- ----------------------------------------------------------------------------------
-- recall_status_status_enum   [enum_domain]   target: gold.fct_recall_status.status
-- purpose : Confirm the tri-state is_active CASE maps to exactly {active,inactive,unknown} and CPSC/NHTSA land in 'unknown'.
-- CONFORMS: status in {active,inactive,unknown} only, never NULL. CPSC and NHTSA rows have status='unknown' only (their is_active is NULL). FDA/USDA/USCG may show active/inactive/unknown.
-- ----------------------------------------------------------------------------------
select source, status, count(*) as n_rows, sum(event_count) as total_events
from gold.fct_recall_status
group by source, status
order by source, status;

-- ----------------------------------------------------------------------------------
-- geography_basis_and_state_seed   [enum_domain]   target: gold.fct_recalls_by_geography.geography_basis, gold.fct_recalls_by_geography.state_code
-- purpose : Confirm geography_basis is the closed {distribution,firm_registration} literal set and every state_code is a us_state_abbr seed member (the constraint is join-enforced but untested).
-- CONFORMS: First query: geography_basis exactly {distribution,firm_registration}. Second query: ZERO rows (every state_code matches the us_state_abbr seed). Any returned state_code is a non-seed leak.
-- VERIFY-NOTE: Two issues: (1) The original used the non-existent table name 'seed_us_state_abbr'; the correct physical table is 'public.us_state_abbr' (seeds land in the default schema per dbt/profiles.yml schema=public with no seeds: schema override in dbt_project.yml). (2) The query was a two-statement block with a bare comment separator — not runnable as a single SQL statement. Corrected to two separate SELECT statements separated by a blank line, both read-only. Column 'abbr' confirmed from dbt/seeds/us_state_abbr.csv header.
-- ----------------------------------------------------------------------------------
select geography_basis, count(*) as n_rows
from gold.fct_recalls_by_geography
group by geography_basis;

select g.state_code, count(*) as n_rows
from gold.fct_recalls_by_geography g
left join public.us_state_abbr usa on usa.abbr = g.state_code
where usa.abbr is null
group by g.state_code;

-- ----------------------------------------------------------------------------------
-- country_code_iso_domain   [enum_domain]   target: gold.fct_recalls_by_country.source, gold.fct_recalls_by_country.country_code
-- purpose : Confirm source in {FDA,USDA,ALL} and country_code is 'US' or a country_iso-seed ISO alpha-2 (the gold model has no accepted_values, relies on silver).
-- CONFORMS: First: source exactly {FDA,USDA,ALL}. Second: ZERO rows (every non-US country_code is in the country_iso seed). Any returned code is an out-of-domain leak.
-- VERIFY-NOTE: Two issues: (1) Original used non-existent table 'seed_country_iso'; correct physical table is 'public.country_iso'. (2) Original joined on 'iso.code' which does not exist — dbt/seeds/country_iso.csv has columns 'name' and 'alpha2' (not 'code'). Corrected join to 'iso.alpha2 = c.country_code'. Also a two-statement block; kept as two separate statements.
-- ----------------------------------------------------------------------------------
select source, count(*) as n_rows
from gold.fct_recalls_by_country
group by source;

select c.country_code, count(*) as n_rows
from gold.fct_recalls_by_country c
left join public.country_iso iso on iso.alpha2 = c.country_code
where c.country_code <> 'US'
  and iso.alpha2 is null
group by c.country_code;

-- ----------------------------------------------------------------------------------
-- gold_facts_empty_string_sweep   [empty_string]   target: gold.fct_recalls_by_firm.canonical_name, gold.fct_recalls_by_geography.state_code, gold.fct_recalls_by_country.country_code, gold.fct_recall_status.status, gold.fct_recalls_by_geography.geography_basis, gold.fct_units_recalled.unit_category, gold.dim_date.month_name, gold.dim_date.day_name
-- purpose : Extend the ''/whitespace probe to every text column in this group. canonical_name is the one real empty-string risk (untrimmed passthrough, outside assert_no_blank_freetext_serving); the others are guarded by construction and should be clean.
-- CONFORMS: n_empty=0 and n_whitespace=0 for ALL rows. canonical_name=0 confirms no firm-name blank leaks into the leaderboard; month_name/day_name=0 confirms the trim(to_char(...)) padding-strip works; the join/literal-guarded columns are 0 by construction.
-- ----------------------------------------------------------------------------------
select 'fct_recalls_by_firm.canonical_name' as col,
       count(*) filter (where canonical_name = '') as n_empty,
       count(*) filter (where canonical_name <> '' and canonical_name ~ '^\s+$') as n_whitespace
from gold.fct_recalls_by_firm
union all
select 'fct_recalls_by_geography.state_code', count(*) filter (where state_code=''), count(*) filter (where state_code<>'' and state_code ~ '^\s+$') from gold.fct_recalls_by_geography
union all
select 'fct_recalls_by_country.country_code', count(*) filter (where country_code=''), count(*) filter (where country_code<>'' and country_code ~ '^\s+$') from gold.fct_recalls_by_country
union all
select 'fct_recall_status.status', count(*) filter (where status=''), count(*) filter (where status<>'' and status ~ '^\s+$') from gold.fct_recall_status
union all
select 'fct_recalls_by_geography.geography_basis', count(*) filter (where geography_basis=''), count(*) filter (where geography_basis<>'' and geography_basis ~ '^\s+$') from gold.fct_recalls_by_geography
union all
select 'fct_units_recalled.unit_category', count(*) filter (where unit_category=''), count(*) filter (where unit_category<>'' and unit_category ~ '^\s+$') from gold.fct_units_recalled
union all
select 'dim_date.month_name', count(*) filter (where month_name=''), count(*) filter (where month_name<>'' and month_name ~ '^\s+$') from gold.dim_date
union all
select 'dim_date.day_name', count(*) filter (where day_name=''), count(*) filter (where day_name<>'' and day_name ~ '^\s+$') from gold.dim_date;

-- ----------------------------------------------------------------------------------
-- classification_empty_string_check   [empty_string]   target: gold.fct_recalls_by_classification.classification, gold.fct_recalls_by_classification.risk_level
-- purpose : Confirm classification/risk_level carry NULL (not '') for the no-value sources — USCG severity and USDA classification are nullif('')-cleaned at staging, so '' must not reach this fact.
-- CONFORMS: cls_empty=0, cls_ws=0, risk_empty=0, risk_ws=0 — the 'no classification' state is represented as NULL, never empty string.
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where classification = '') as cls_empty,
  count(*) filter (where classification <> '' and classification ~ '^\s+$') as cls_ws,
  count(*) filter (where risk_level = '') as risk_empty,
  count(*) filter (where risk_level <> '' and risk_level ~ '^\s+$') as risk_ws
from gold.fct_recalls_by_classification;

-- ----------------------------------------------------------------------------------
-- period_columns_not_null   [nullability]   target: gold.fct_recalls_by_month.period, gold.fct_recalls_by_week.period, gold.fct_recalls_by_year.period, gold.fct_recalls_monthly_trend.month, gold.fct_units_recalled.period
-- purpose : Confirm every period/month column is non-null (the dim_date INNER JOIN on published_at::date is asserted lossless; a NULL period would mean a recall published outside the spine).
-- CONFORMS: n_null_period = 0 for every object (lossless dim_date join; spine floor 1940 matches the recall_event date-sanity floor).
-- ----------------------------------------------------------------------------------
select 'by_month' as obj, count(*) filter (where period is null) as n_null_period from gold.fct_recalls_by_month
union all select 'by_week', count(*) filter (where period is null) from gold.fct_recalls_by_week
union all select 'by_year', count(*) filter (where period is null) from gold.fct_recalls_by_year
union all select 'monthly_trend', count(*) filter (where month is null) from gold.fct_recalls_monthly_trend
union all select 'units_recalled', count(*) filter (where period is null) from gold.fct_units_recalled;

-- ----------------------------------------------------------------------------------
-- count_measures_not_null_nonneg   [range_sanity]   target: gold.fct_recalls_by_month.event_count, gold.fct_recalls_by_classification.event_count, gold.fct_recall_status.event_count, gold.fct_recalls_by_geography.recall_count, gold.fct_recalls_by_country.recall_count, gold.fct_units_recalled.total_units
-- purpose : Confirm count/measure columns are non-null and non-negative (count(distinct ...) and sum(units) cannot be negative; total_units is NOT NULL per _gold.yml).
-- CONFORMS: n_bad = 0 for every measure (all counts/sums non-null and >= 0).
-- ----------------------------------------------------------------------------------
select 'by_month.event_count' as col, count(*) filter (where event_count is null or event_count < 0) as n_bad from gold.fct_recalls_by_month
union all select 'by_classification.event_count', count(*) filter (where event_count is null or event_count<0) from gold.fct_recalls_by_classification
union all select 'recall_status.event_count', count(*) filter (where event_count is null or event_count<0) from gold.fct_recall_status
union all select 'by_geography.recall_count', count(*) filter (where recall_count is null or recall_count<0) from gold.fct_recalls_by_geography
union all select 'by_country.recall_count', count(*) filter (where recall_count is null or recall_count<0) from gold.fct_recalls_by_country
union all select 'units_recalled.total_units', count(*) filter (where total_units is null or total_units<0) from gold.fct_units_recalled;

-- ----------------------------------------------------------------------------------
-- dim_date_grain_and_range   [range_sanity]   target: gold.dim_date.date_day
-- purpose : Confirm one-row-per-day uniqueness and that the spine spans exactly 1940-01-01 .. (current year+2) with no gaps — the lossless-join precondition for the date-grained facts.
-- CONFORMS: n_rows = n_distinct = expected_rows (contiguous, no gaps/dupes); min_day = 1940-01-01; max_day in the (current_year+1 .. current_year+2) Dec-31 region (dynamic). date_day unique.
-- ----------------------------------------------------------------------------------
select
  count(*) as n_rows,
  count(distinct date_day) as n_distinct,
  min(date_day) as min_day,
  max(date_day) as max_day,
  (max(date_day) - min(date_day) + 1) as expected_rows
from gold.dim_date;

-- ----------------------------------------------------------------------------------
-- fct_recalls_by_firm_grain   [grain]   target: gold.fct_recalls_by_firm.firm_id
-- purpose : Confirm the leaderboard is one-row-per-canonical-firm (firm_id unique) and firm_id is non-null (relationships test backing).
-- CONFORMS: n_rows = n_distinct (firm_id unique, one row per canonical firm); n_null_firm_id = 0.
-- ----------------------------------------------------------------------------------
select count(*) as n_rows, count(distinct firm_id) as n_distinct,
  count(*) filter (where firm_id is null) as n_null_firm_id
from gold.fct_recalls_by_firm;

-- ----------------------------------------------------------------------------------
-- grouped_facts_grain_uniqueness   [grain]   target: gold.fct_recalls_by_month, gold.fct_recall_status, gold.fct_recalls_by_classification, gold.fct_recalls_by_geography, gold.fct_units_recalled
-- purpose : Confirm each grouped fact's row count equals its distinct grain-tuple count (GROUPING SETS must not duplicate a cell).
-- CONFORMS: For each object n_rows = n_grain. NOTE: count(distinct tuple) treats NULL components (classification/risk_level) as a single NULL bucket, matching GROUPING SETS semantics; if a discrepancy appears it is a true grain duplication.
-- ----------------------------------------------------------------------------------
select 'by_month' as obj, count(*) as n_rows, count(distinct (period, source)) as n_grain from gold.fct_recalls_by_month
union all select 'recall_status', count(*), count(distinct (source, status)) from gold.fct_recall_status
union all select 'by_classification', count(*), count(distinct (source, classification, risk_level)) from gold.fct_recalls_by_classification
union all select 'by_geography', count(*), count(distinct (geography_basis, source, state_code)) from gold.fct_recalls_by_geography
union all select 'units_recalled', count(*), count(distinct (source, unit_category, period)) from gold.fct_units_recalled;

-- ----------------------------------------------------------------------------------
-- monthly_trend_window_sanity   [range_sanity]   target: gold.fct_recalls_monthly_trend.event_count, gold.fct_recalls_monthly_trend.rolling_3mo_avg, gold.fct_recalls_monthly_trend.event_count_year_ago
-- purpose : Confirm the dense-spine window outputs are sane: event_count never NULL (0-filled), rolling avgs non-null/non-negative, event_count_year_ago/yoy_pct_change NULL only in the first 12 months per source or when year-ago=0.
-- CONFORMS: bad_event_count=0, bad_r3=0, bad_r12=0 (event_count 0-coalesced, rolling avgs always defined and >=0). neg_year_ago=0 (lag of a non-negative count). NULLs in event_count_year_ago/yoy_pct_change are allowed (first 12 months / year-ago=0).
-- ----------------------------------------------------------------------------------
select
  count(*) filter (where event_count is null or event_count < 0) as bad_event_count,
  count(*) filter (where rolling_3mo_avg is null or rolling_3mo_avg < 0) as bad_r3,
  count(*) filter (where rolling_12mo_avg is null or rolling_12mo_avg < 0) as bad_r12,
  count(*) filter (where event_count_year_ago < 0) as neg_year_ago
from gold.fct_recalls_monthly_trend;
